#!/usr/bin/env python3
"""Enzyme fallback report — quiet-day observability tool for ADR 017 gate 5a.

Queries the DLT pipeline event log for the GOLD pipeline and emits, per materialized
view (flow), the most-recent Enzyme planning mode (NO_OP / ROW_BASED / COMPLETE_RECOMPUTE)
and — where a flow fell back to COMPLETE_RECOMPUTE — the event-log fallback *reason*
as emitted by Enzyme in the ``flow_progress`` / ``planning_information`` detail block.

The reason is READ FROM THE EVENT LOG, not inferred from SQL shape. ADR 017 gate 5a
is explicit: the rewrite-candidate list must be data-driven, not guessed.

## Event-log schema grounding

DLT pipeline event logs are queryable at two surfaces:

1. ``system.lakeflow.pipeline_events`` (Unity Catalog system table, available if the
   workspace has system-table access granted). Columns:
       pipeline_id STRING, event_id STRING, timestamp TIMESTAMP, sequence STRUCT,
       origin STRUCT<pipeline_name,flow_name,flow_id,table_name,...>,
       event_type STRING,       -- e.g. 'flow_progress'
       level STRING,            -- 'INFO', 'WARN', 'ERROR', 'METRICS'
       message STRING,
       details STRING           -- JSON blob; Enzyme planning lives here
       maturity_level STRING

2. Pipeline-local ``event_log`` table, exposed inside a DLT pipeline's storage location
   as a Delta table. Queried as ``<catalog>.<schema>.event_log`` where the schema matches
   the pipeline's target schema, or via the pipeline API.

For this script the System Table surface is used when ``PIPELINE_ID`` is known; it falls
back to the pipeline-scoped ``event_log`` table in the configured gold schema otherwise.

The ``details`` JSON for an Enzyme planning event has this shape (Databricks DLT
internals, verified against pipeline UI 2026-06-12):

    {
      "flow_progress": {
        "status": "RUNNING" | "COMPLETED" | "FAILED",
        "planning_information": {
          "planning_mode": "NO_OP" | "ROW_BASED" | "COMPLETE_RECOMPUTE",
          "reason": "<human-readable reason string — only present for COMPLETE_RECOMPUTE>",
          "rows_affected": 12345   -- present for ROW_BASED / COMPLETE_RECOMPUTE
        }
      }
    }

The ``event_type`` for these rows is ``flow_progress``.  ``level`` is ``INFO``.
Only rows where ``details:flow_progress.planning_information`` is non-null carry
planning-mode data — other ``flow_progress`` events (e.g. startup/completion signals
without planning detail) do not.

## Usage

Run against a Databricks SQL warehouse using the Databricks SQL connector, or paste
the generated SQL into the Databricks SQL editor directly.

    python data-products/io-reporting/scripts/enzyme_fallback_report.py \\
        --pipeline-id <gold-pipeline-uuid> \\
        --catalog connected_plant_uat \\
        --gold-schema gold_io_reporting \\
        [--warehouse-id <sql-warehouse-id>] \\
        [--profile DEFAULT]

If ``--warehouse-id`` is omitted the SQL is printed to stdout for manual execution
in the Databricks SQL editor (the typical quiet-day workflow).

## ADR 017 gate context

Pull this report on a **quiet day** (no estate-gate expansion, no full-recompute
pipeline run in progress) to get a representative steady-state planning-mode
distribution. A contaminated day (e.g. 2026-06-12 where QM lots expanded 505k→9M)
inflates COMPLETE_RECOMPUTE share.

The report drives the flow-rewrite candidate list (journey events, SPC subgroup,
QM lot tables, event ledger). A flow is a rewrite candidate ONLY when it is
persistently COMPLETE_RECOMPUTE *and* material in cost *and* subject to a genuine
sub-15-minute SLA (ADR 017 decision 1 three-part test).
"""
from __future__ import annotations

import argparse
import sys
import textwrap

# ---------------------------------------------------------------------------
# SQL
# ---------------------------------------------------------------------------

# This query uses the system.lakeflow.pipeline_events surface.
# Replace ``@pipeline_id`` with the gold pipeline's UUID.
# Replace ``@lookback_days`` with how many days of history to scan (default 7).
_SYSTEM_TABLE_SQL = textwrap.dedent("""\
    -- Enzyme fallback report — ADR 017 gate 5a
    -- Surface: system.lakeflow.pipeline_events
    -- Generated by: data-products/io-reporting/scripts/enzyme_fallback_report.py
    --
    -- For each gold materialized-view flow, returns the LATEST planning-mode decision
    -- and (where COMPLETE_RECOMPUTE) the Enzyme fallback reason from the event-log
    -- detail JSON.  Sorted by recompute cost proxy (rows_affected DESC).

    WITH raw_planning AS (
      SELECT
        pe.pipeline_id,
        pe.origin.flow_name                                         AS flow_name,
        pe.timestamp                                                AS event_ts,
        pe.details:flow_progress.planning_information.planning_mode AS planning_mode,
        pe.details:flow_progress.planning_information.reason        AS fallback_reason,
        CAST(
          pe.details:flow_progress.planning_information.rows_affected
          AS BIGINT
        )                                                           AS rows_affected,
        ROW_NUMBER() OVER (
          PARTITION BY pe.pipeline_id, pe.origin.flow_name
          ORDER BY pe.timestamp DESC
        )                                                           AS rn
      FROM system.lakeflow.pipeline_events pe
      WHERE
        pe.pipeline_id    = '{pipeline_id}'
        AND pe.event_type = 'flow_progress'
        AND pe.level      = 'INFO'
        AND pe.timestamp  >= DATEADD(DAY, -{lookback_days}, CURRENT_TIMESTAMP())
        -- Only rows that carry Enzyme planning-mode detail
        AND pe.details:flow_progress.planning_information.planning_mode IS NOT NULL
    )
    SELECT
      flow_name,
      planning_mode,
      CASE
        WHEN planning_mode = 'COMPLETE_RECOMPUTE' THEN fallback_reason
        ELSE NULL
      END                                                           AS fallback_reason,
      rows_affected,
      event_ts                                                      AS last_planning_ts
    FROM raw_planning
    WHERE rn = 1
    ORDER BY
      -- Recompute-cost proxy: COMPLETE_RECOMPUTE first, then by rows affected DESC
      CASE planning_mode
        WHEN 'COMPLETE_RECOMPUTE' THEN 0
        WHEN 'ROW_BASED'          THEN 1
        WHEN 'NO_OP'              THEN 2
        ELSE 3
      END,
      rows_affected DESC NULLS LAST;
""")

# Fallback query against the pipeline-scoped event_log table (when system tables
# are unavailable).  The schema is the same as system.lakeflow.pipeline_events but
# the table is local to the pipeline's storage location.  In practice, query it as
# <catalog>.<gold_schema>.event_log in a Databricks SQL editor session that has
# USE CATALOG / USE SCHEMA set, or with a fully qualified reference.
_PIPELINE_LOCAL_SQL = textwrap.dedent("""\
    -- Enzyme fallback report — ADR 017 gate 5a
    -- Surface: pipeline-local event_log table
    -- Generated by: data-products/io-reporting/scripts/enzyme_fallback_report.py
    --
    -- Set the catalog/schema before running:
    --   USE CATALOG {catalog};
    --   USE SCHEMA {gold_schema};

    WITH raw_planning AS (
      SELECT
        origin.flow_name                                            AS flow_name,
        timestamp                                                   AS event_ts,
        details:flow_progress.planning_information.planning_mode   AS planning_mode,
        details:flow_progress.planning_information.reason          AS fallback_reason,
        CAST(
          details:flow_progress.planning_information.rows_affected
          AS BIGINT
        )                                                           AS rows_affected,
        ROW_NUMBER() OVER (
          PARTITION BY origin.flow_name
          ORDER BY timestamp DESC
        )                                                           AS rn
      FROM event_log
      WHERE
        event_type = 'flow_progress'
        AND level  = 'INFO'
        AND timestamp >= DATEADD(DAY, -{lookback_days}, CURRENT_TIMESTAMP())
        AND details:flow_progress.planning_information.planning_mode IS NOT NULL
    )
    SELECT
      flow_name,
      planning_mode,
      CASE
        WHEN planning_mode = 'COMPLETE_RECOMPUTE' THEN fallback_reason
        ELSE NULL
      END                                                           AS fallback_reason,
      rows_affected,
      event_ts                                                      AS last_planning_ts
    FROM raw_planning
    WHERE rn = 1
    ORDER BY
      CASE planning_mode
        WHEN 'COMPLETE_RECOMPUTE' THEN 0
        WHEN 'ROW_BASED'          THEN 1
        WHEN 'NO_OP'              THEN 2
        ELSE 3
      END,
      rows_affected DESC NULLS LAST;
""")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Emit the Enzyme fallback report for the gold pipeline (ADR 017 gate 5a).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              # Print SQL for manual execution (no warehouse required):
              python enzyme_fallback_report.py \\
                  --pipeline-id abc-123 \\
                  --catalog connected_plant_uat \\
                  --gold-schema gold_io_reporting

              # Execute against a SQL warehouse and print results:
              python enzyme_fallback_report.py \\
                  --pipeline-id abc-123 \\
                  --catalog connected_plant_uat \\
                  --gold-schema gold_io_reporting \\
                  --warehouse-id e2aXXXXXXXXXXXXX \\
                  --profile DEFAULT
        """),
    )
    p.add_argument(
        "--pipeline-id",
        required=True,
        help="UUID of the gold DLT pipeline (from Databricks Pipelines UI or `databricks pipelines list`).",
    )
    p.add_argument(
        "--catalog",
        default="connected_plant_uat",
        help="Unity Catalog catalog name (default: connected_plant_uat).",
    )
    p.add_argument(
        "--gold-schema",
        default="gold_io_reporting",
        help="Gold schema name (default: gold_io_reporting).",
    )
    p.add_argument(
        "--lookback-days",
        type=int,
        default=7,
        help="How many days of pipeline event history to scan (default: 7).",
    )
    p.add_argument(
        "--warehouse-id",
        default=None,
        help=(
            "Databricks SQL warehouse ID. If omitted the SQL is printed to stdout "
            "for manual execution."
        ),
    )
    p.add_argument(
        "--profile",
        default="DEFAULT",
        help="Databricks CLI profile (default: DEFAULT).",
    )
    p.add_argument(
        "--use-local-event-log",
        action="store_true",
        default=False,
        help=(
            "Use the pipeline-local event_log table instead of "
            "system.lakeflow.pipeline_events. Use when system-table access is "
            "not granted."
        ),
    )
    return p


def _render_sql(pipeline_id: str, catalog: str, gold_schema: str, lookback_days: int, local: bool) -> str:
    if local:
        return _PIPELINE_LOCAL_SQL.format(
            catalog=catalog,
            gold_schema=gold_schema,
            lookback_days=lookback_days,
        )
    return _SYSTEM_TABLE_SQL.format(
        pipeline_id=pipeline_id,
        lookback_days=lookback_days,
    )


def _execute_via_sdk(sql: str, warehouse_id: str, profile: str) -> None:
    """Execute the SQL against a Databricks SQL warehouse and pretty-print results.

    Requires: databricks-sdk (pip install databricks-sdk).
    """
    try:
        from databricks.sdk import WorkspaceClient  # type: ignore[import]
    except ImportError:
        print(
            "ERROR: databricks-sdk is not installed. Install it with:\n"
            "  pip install databricks-sdk\n"
            "Or omit --warehouse-id to print the SQL for manual execution.",
            file=sys.stderr,
        )
        sys.exit(1)

    w = WorkspaceClient(profile=profile)
    print(f"Executing query against warehouse {warehouse_id} ...\n")
    result = w.statement_execution.execute_statement(
        warehouse_id=warehouse_id,
        statement=sql,
        wait_timeout="30s",
    )

    status = result.status
    if status and status.state.name not in ("SUCCEEDED",):
        print(f"Query failed: {status.error}", file=sys.stderr)
        sys.exit(1)

    manifest = result.manifest
    data = result.result

    if not manifest or not manifest.schema or not manifest.schema.columns:
        print("No schema returned — pipeline may have no planning events in the lookback window.")
        return

    headers = [col.name for col in manifest.schema.columns]

    rows = []
    if data and data.data_array:
        rows = data.data_array

    if not rows:
        print("No Enzyme planning events found in the lookback window.")
        print("This is normal if the pipeline has not run since the lookback start,")
        print("or if planning-information events are not yet in the system table.")
        return

    # Pretty-print as a tidy table
    col_widths = [len(h) for h in headers]
    str_rows = []
    for row in rows:
        sr = [str(v) if v is not None else "NULL" for v in row]
        for i, v in enumerate(sr):
            col_widths[i] = max(col_widths[i], len(v))
        str_rows.append(sr)

    sep = "+" + "+".join("-" * (w + 2) for w in col_widths) + "+"
    header_line = "|" + "|".join(f" {h:<{col_widths[i]}} " for i, h in enumerate(headers)) + "|"
    print(sep)
    print(header_line)
    print(sep)
    for row in str_rows:
        print("|" + "|".join(f" {v:<{col_widths[i]}} " for i, v in enumerate(row)) + "|")
    print(sep)
    print(f"\n{len(str_rows)} flow(s) returned.")

    # Summarise COMPLETE_RECOMPUTE share
    mode_idx = headers.index("planning_mode") if "planning_mode" in headers else -1
    if mode_idx >= 0:
        modes = [r[mode_idx] for r in str_rows]
        total = len(modes)
        recompute = sum(1 for m in modes if m == "COMPLETE_RECOMPUTE")
        row_based = sum(1 for m in modes if m == "ROW_BASED")
        no_op = sum(1 for m in modes if m == "NO_OP")
        print(
            f"\nSummary: {total} flows — "
            f"NO_OP={no_op} ({no_op*100//total}%), "
            f"ROW_BASED={row_based} ({row_based*100//total}%), "
            f"COMPLETE_RECOMPUTE={recompute} ({recompute*100//total}%)"
        )
        if recompute > 0:
            print(
                "\nADR 017 note: a flow is a streaming-table rewrite CANDIDATE only when it is"
                "\npersistently COMPLETE_RECOMPUTE AND material in cost AND subject to a genuine"
                "\nsub-15-min SLA (three-part test, decision 1). Review fallback_reason to triage."
            )


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    sql = _render_sql(
        pipeline_id=args.pipeline_id,
        catalog=args.catalog,
        gold_schema=args.gold_schema,
        lookback_days=args.lookback_days,
        local=args.use_local_event_log,
    )

    if args.warehouse_id is None:
        print("-- Paste the following SQL into the Databricks SQL editor.")
        print("-- For local event_log: run USE CATALOG / USE SCHEMA first.")
        print()
        print(sql)
        print()
        print("-- To execute programmatically, rerun with --warehouse-id <id>.")
        return 0

    _execute_via_sdk(sql, args.warehouse_id, args.profile)
    return 0


if __name__ == "__main__":
    sys.exit(main())
