#!/usr/bin/env python3
"""
Generate environment-specific Unity Catalog base-metadata SQL for Silver and Gold tables.

For each table declared in metadata/silver/*.metadata.yml and metadata/gold/*.metadata.yml,
emit three types of UC admin statements (per environment):

  1. COMMENT ON TABLE <catalog>.<schema>.<table> IS '...'
     Emitted only when the table comment is non-empty (blank in P0 — populated in backfill).

  2. ALTER TABLE <catalog>.<schema>.<table> SET TAGS (...)
     Embeds product_area, gating_category, current_status, source_tables, and layer as UC
     object tags for discoverability and governance.

  3. COMMENT ON COLUMN <catalog>.<schema>.<table>.<col> IS '...'
     Emitted only for columns whose comment is non-empty (blank in P0 — populated in backfill).

UC syntax notes (verified against Databricks documentation):
  - ALTER TABLE ... SET TAGS (key = value) IS SUPPORTED on tables, streaming tables, and MVs.
  - COMMENT ON TABLE ... IS '...' IS SUPPORTED on all relation types.
  - COMMENT ON COLUMN ... IS '...' IS SUPPORTED on tables, streaming tables, and MVs.
    (Databricks docs: relation_name may be a table, view, streaming table, or MV.)

Re-runnable: COMMENT ON and SET TAGS are idempotent (they overwrite existing values). Run
once as a UC admin after the DLT pipeline has created the tables, or whenever the metadata
YAMLs are updated.

IMPORTANT: SET TAGS must be re-applied after any DLT full-refresh that re-creates the table
object, because Databricks drops UC tags on table recreation. Schedule this script as a
post-refresh hook or run it manually after each full-refresh deploy.

Outputs SQL to resources/sql/silver_metadata_{dev,uat,prod}.sql and
gold_metadata_{dev,uat,prod}.sql.
"""
import argparse
import pathlib
import re
import sys

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML is required: pip install pyyaml")

# Default base directory: the repo product root (parent of this script's directory).
_DEFAULT_BASE_DIR = pathlib.Path(__file__).resolve().parent.parent

ENVIRONMENTS = {
    "dev": {
        "catalog": "connected_plant_dev",
        "silver_schema": "silver_io_reporting",
        "gold_schema": "gold_io_reporting",
    },
    "uat": {
        "catalog": "connected_plant_uat",
        "silver_schema": "silver_io_reporting",
        "gold_schema": "gold_io_reporting",
    },
    "prod": {
        "catalog": "connected_plant_prod",
        "silver_schema": "silver_io_reporting",
        "gold_schema": "gold_io_reporting",
    },
}

SILVER_METADATA_GLOB = "metadata/silver/*.metadata.yml"
GOLD_METADATA_GLOB = "metadata/gold/*.metadata.yml"

HEADER_TEMPLATE = """\
-- Unity Catalog base metadata — {layer} table annotations ({env_upper}).
-- Generated by scripts/generate_base_metadata_sql.py — do not edit manually.
-- Run once as a UC admin after the DLT pipeline has created the tables.
-- Re-runnable: COMMENT ON and SET TAGS are idempotent (they overwrite existing values).
--
-- IMPORTANT: SET TAGS must be re-applied after any DLT full-refresh that re-creates the
-- table object (Databricks drops UC tags on table recreation).
--
-- Covers {table_count} table(s) across {file_count} metadata file(s).
-- Column comments are omitted where blank (P0 skeleton — populated in backfill phase).
--
-- UC syntax used:
--   COMMENT ON TABLE ... IS '...'          (table-level description, when non-empty)
--   ALTER TABLE ... SET TAGS (...)         (machine-readable governance tags)
--   COMMENT ON COLUMN ... IS '...'        (column-level descriptions, when non-empty)
--
-- Requires: APPLY TAG + MODIFY / OWNER on the target tables in {qualified_schema}.
"""


def _escape_sql_string(text: str) -> str:
    """Escape single quotes in a SQL string literal by doubling them."""
    return text.replace("'", "''")


def _is_blank(value) -> bool:
    """True if value is None or an empty/whitespace-only string."""
    if value is None:
        return True
    return not str(value).strip()


def _load_metadata_files(base_dir: pathlib.Path, glob_pattern: str) -> list[dict]:
    """Load and merge all YAML metadata files matching the glob pattern."""
    files = sorted(base_dir.glob(glob_pattern))
    all_tables: list[dict] = []
    for f in files:
        content = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
        for tbl in content.get("tables") or []:
            tbl["_source_file"] = f.name
            all_tables.append(tbl)
    return all_tables, len(files)


def generate_sql(
    env_filter: str | None = None,
    layer_filter: str | None = None,
    base_dir: pathlib.Path | None = None,
) -> None:
    """Write base metadata SQL files to resources/sql/.

    Args:
        env_filter: restrict generation to one of dev/uat/prod; None generates all.
        layer_filter: restrict to 'silver' or 'gold'; None generates both.
        base_dir: product root directory (parent of scripts/). Defaults to the repo
            product root. Tests pass a tmp_path here to avoid writing to committed files.
    """
    if base_dir is None:
        base_dir = _DEFAULT_BASE_DIR
    base_dir = pathlib.Path(base_dir)

    if env_filter and env_filter not in ENVIRONMENTS:
        raise SystemExit(
            f"Unknown --env '{env_filter}' (allowed: {', '.join(ENVIRONMENTS)})."
        )

    layers = []
    if layer_filter in (None, "silver"):
        layers.append("silver")
    if layer_filter in (None, "gold"):
        layers.append("gold")

    if not layers:
        raise SystemExit(f"Unknown --layer '{layer_filter}' (allowed: silver, gold).")

    out_dir = base_dir / "resources" / "sql"
    out_dir.mkdir(parents=True, exist_ok=True)

    envs = {env_filter: ENVIRONMENTS[env_filter]} if env_filter else ENVIRONMENTS

    for layer in layers:
        glob = SILVER_METADATA_GLOB if layer == "silver" else GOLD_METADATA_GLOB
        tables, file_count = _load_metadata_files(base_dir, glob)
        if not tables:
            print(f"WARNING: No metadata files found for {layer} (pattern: {glob})")

        for env, cfg in envs.items():
            catalog = cfg["catalog"]
            schema = cfg[f"{layer}_schema"]
            qualified_schema = f"{catalog}.{schema}"

            body_parts: list[str] = []

            for tbl in tables:
                table_name = tbl.get("name", "")
                if not table_name:
                    continue

                qualified_table = f"{qualified_schema}.{table_name}"
                section: list[str] = []
                section.append(f"-- ── Table: {table_name} (from {tbl.get('_source_file', '?')}) ──")

                # 1. COMMENT ON TABLE (only if non-empty)
                table_comment = str(tbl.get("comment") or "").strip()
                if table_comment:
                    escaped = _escape_sql_string(re.sub(r"\s*\n\s*", " ", table_comment))
                    section.append(
                        f"COMMENT ON TABLE {qualified_table} IS\n"
                        f"  '{escaped}';"
                    )

                # 2. SET TAGS — always emit (governance tags are unconditional in P0)
                tags: dict = tbl.get("tags") or {}
                tag_pairs = []
                for k, v in tags.items():
                    if k == "_source_file":
                        continue
                    escaped_k = _escape_sql_string(str(k))
                    escaped_v = _escape_sql_string(str(v) if v is not None else "")
                    tag_pairs.append(f"  '{escaped_k}' = '{escaped_v}'")
                if tag_pairs:
                    section.append(
                        f"ALTER TABLE {qualified_table} SET TAGS (\n"
                        + ",\n".join(tag_pairs)
                        + "\n);"
                    )

                # 3. COMMENT ON COLUMN (only for columns with non-empty comments)
                columns = tbl.get("columns") or []
                col_comments: list[str] = []
                for col in columns:
                    col_name = col.get("name", "")
                    col_comment = str(col.get("comment") or "").strip()
                    if not col_name or not col_comment:
                        continue
                    desc_clean = re.sub(r"\s*\n\s*", " ", col_comment)
                    escaped_desc = _escape_sql_string(desc_clean)
                    col_comments.append(
                        f"COMMENT ON COLUMN {qualified_table}.{col_name} IS\n"
                        f"  '{escaped_desc}';"
                    )
                if col_comments:
                    section.extend(col_comments)
                else:
                    section.append(
                        f"-- (no column comments yet for {table_name} — populate in backfill phase)"
                    )

                body_parts.append("\n".join(section))

            header = HEADER_TEMPLATE.format(
                layer=layer.upper(),
                env_upper=env.upper(),
                table_count=len(tables),
                file_count=file_count,
                qualified_schema=qualified_schema,
            )

            sql = header + "\n" + "\n\n".join(body_parts) + "\n"

            out_path = out_dir / f"{layer}_metadata_{env}.sql"
            with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(sql)

            print(
                f"Generated: {out_path}  "
                f"({len(tables)} tables, {file_count} source files)"
            )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Generate Unity Catalog base-metadata SQL "
            "(COMMENT ON TABLE, SET TAGS, COMMENT ON COLUMN)."
        )
    )
    parser.add_argument(
        "--env",
        choices=list(ENVIRONMENTS),
        default=None,
        help="Restrict generation to one environment (default: all three).",
    )
    parser.add_argument(
        "--layer",
        choices=["silver", "gold"],
        default=None,
        help="Restrict generation to one layer (default: both).",
    )
    args = parser.parse_args(argv)
    generate_sql(env_filter=args.env, layer_filter=args.layer)
    return 0


if __name__ == "__main__":
    sys.exit(main())
