#!/usr/bin/env python3
"""
Generate environment-specific Unity Catalog contract-metadata SQL.

For each contract in app_contract_manifest.yml that has a source_view matching an
actual consumption view in resources/sql/*consumption_views_<env>.sql, emit three
types of UC admin statements:

  1. COMMENT ON VIEW <catalog>.<schema>.<view> IS '...'
     Composed from: description (first paragraph), grain, contract id+version,
     freshness SLA, and access/row-level key.

  2. ALTER VIEW <catalog>.<schema>.<view> SET TAGS (...)
     Embeds contract_id, contract_version, contract_grain, and
     freshness_expected_minutes as UC object tags.

  3. COMMENT ON COLUMN <catalog>.<schema>.<view>.<col> IS '...'
     Emitted for every field in the contract that carries a description.

UC syntax notes (verified against Databricks documentation):
  - ALTER VIEW ... SET TAGS (key = value) IS SUPPORTED on views.
  - ALTER VIEW ... ALTER COLUMN ... COMMENT IS NOT SUPPORTED on views.
  - COMMENT ON COLUMN <view>.<col> IS '...' IS SUPPORTED on views.
    (Databricks docs: relation_name may be a table, view, streaming table, or MV.)
  - The generator therefore uses COMMENT ON COLUMN — not ALTER COLUMN COMMENT.

Re-runnable: COMMENT ON and SET TAGS are idempotent (they overwrite). Run once as a
UC admin after the consumption views are created or whenever the manifest is updated.

Outputs SQL to resources/sql/contract_metadata_{dev,uat,prod}.sql.
"""
import argparse
import pathlib
import re
import sys

try:
    import yaml
except ImportError:
    raise SystemExit(
        "PyYAML is required: pip install pyyaml"
    )

# Default base directory: the repo product root (parent of this script's directory).
_DEFAULT_BASE_DIR = pathlib.Path(__file__).resolve().parent.parent

ENVIRONMENTS = {
    "dev": {
        "catalog": "connected_plant_dev",
        "gold_schema": "gold_io_reporting",
    },
    "uat": {
        "catalog": "connected_plant_uat",
        "gold_schema": "gold_io_reporting",
    },
    "prod": {
        "catalog": "connected_plant_prod",
        "gold_schema": "gold_io_reporting",
    },
}

# Relative path (from base_dir) to the single source-of-truth manifest.
MANIFEST_PATH = "contracts/app_contract_manifest.yml"

# Glob pattern for consumption-view SQL files in resources/sql/.
CONSUMPTION_VIEW_GLOB = "resources/sql/*consumption_views_{env}.sql"

HEADER_TEMPLATE = """\
-- Unity Catalog contract metadata — consumption-view annotations ({env_upper}).
-- Generated by scripts/generate_contract_metadata_sql.py — do not edit manually.
-- Run once as a UC admin after the consumption views are created / updated.
-- Re-runnable: COMMENT ON and SET TAGS are idempotent (they overwrite existing values).
--
-- Covers {covered} contract(s) with a matched source_view.
-- Skipped {skipped} contract(s) whose source_view is not yet created in
-- resources/sql/*consumption_views_{env_lower}.sql (see generator output for details).
--
-- UC syntax used:
--   COMMENT ON VIEW ... IS '...'              (view-level description)
--   ALTER VIEW ... SET TAGS (...)             (machine-readable contract metadata)
--   COMMENT ON COLUMN ... IS '...'           (column-level descriptions visible in
--                                             Genie / data explorer / AI agents)
--
-- Requires: APPLY TAG + MODIFY / OWNER on the target views in {catalog}.{gold_schema}.
"""


def _escape_sql_string(text: str) -> str:
    """Escape single quotes in a SQL string literal by doubling them."""
    return text.replace("'", "''")


def _first_paragraph(text: str) -> str:
    """Return the first non-empty paragraph of a YAML block scalar, stripped of excess
    whitespace and with internal newlines collapsed to spaces."""
    # YAML block scalars can have trailing newlines and indentation already handled by
    # the YAML loader, but may contain embedded newlines splitting long sentences.
    paragraphs = re.split(r"\n\s*\n", text.strip())
    if not paragraphs:
        return text.strip()
    first = paragraphs[0].strip()
    # Collapse internal line breaks to single spaces (flow-style).
    return re.sub(r"\s*\n\s*", " ", first)


def _build_view_comment(contract: dict) -> str:
    """Compose the view-level COMMENT text from contract metadata."""
    desc = _first_paragraph(str(contract.get("description", "")).strip())
    grain = str(contract.get("grain", "")).strip()
    cid = contract.get("id", "")
    version = contract.get("version", "")
    freshness = contract.get("freshness") or {}
    expected = freshness.get("expected_minutes", "")
    warning = freshness.get("warning_minutes", "")
    critical = freshness.get("critical_minutes", "")
    row_key = (contract.get("access_policy") or {}).get("row_level_key", "")

    parts = []
    if desc:
        parts.append(desc)
    if grain:
        parts.append(f"Grain: {grain}.")
    if cid:
        v_str = f" v{version}" if version else ""
        parts.append(f"Contract: {cid}{v_str}.")
    freshness_parts = []
    if expected:
        freshness_parts.append(f"expected {expected} min")
    if warning:
        freshness_parts.append(f"warning {warning} min")
    if critical:
        freshness_parts.append(f"critical {critical} min")
    if freshness_parts:
        parts.append(f"Freshness SLA: {', '.join(freshness_parts)}.")
    if row_key:
        parts.append(f"Row-level access key: {row_key}.")

    return " ".join(parts)


def _collect_view_names_from_sql(env: str, base_dir: pathlib.Path) -> set[str]:
    """Parse all *consumption_views_<env>.sql files and return the set of view names
    defined via 'CREATE OR REPLACE VIEW <name>' (unqualified name only)."""
    pattern = CONSUMPTION_VIEW_GLOB.format(env=env)
    sql_files = list(base_dir.glob(pattern))
    view_names: set[str] = set()
    for sql_file in sql_files:
        text = sql_file.read_text(encoding="utf-8")
        for m in re.finditer(
            r"CREATE\s+OR\s+REPLACE\s+VIEW\s+(?:`?\w+`?\.)*`?(\w+)`?\s+AS",
            text,
            re.IGNORECASE,
        ):
            view_names.add(m.group(1))
    return view_names


def generate_sql(env_filter: str | None = None, base_dir: pathlib.Path | None = None):
    """Write contract metadata SQL files to resources/sql/.

    Args:
        env_filter: restrict generation to one of dev/uat/prod; None generates all.
        base_dir: product root directory (parent of scripts/). Defaults to the repo
            product root. Tests pass a tmp_path here to avoid writing to committed files.
    """
    if base_dir is None:
        base_dir = _DEFAULT_BASE_DIR
    base_dir = pathlib.Path(base_dir)

    if env_filter and env_filter not in ENVIRONMENTS:
        raise SystemExit(
            f"Unknown --env '{env_filter}' (allowed: {', '.join(ENVIRONMENTS)})."
        )

    manifest_path = base_dir / MANIFEST_PATH
    if not manifest_path.exists():
        raise SystemExit(f"Manifest not found: {manifest_path}")

    with open(manifest_path, encoding="utf-8") as f:
        manifest = yaml.safe_load(f) or {}

    contracts = manifest.get("contracts") or []

    (base_dir / "resources" / "sql").mkdir(parents=True, exist_ok=True)

    envs = {env_filter: ENVIRONMENTS[env_filter]} if env_filter else ENVIRONMENTS

    for env, cfg in envs.items():
        catalog = cfg["catalog"]
        schema = cfg["gold_schema"]
        qualified_schema = f"{catalog}.{schema}"

        # Collect the actual view names for this env from the SQL files.
        existing_views = _collect_view_names_from_sql(env, base_dir)

        covered = []
        skipped = []

        body_parts: list[str] = []

        for contract in contracts:
            source_view = contract.get("source_view")
            if not source_view:
                skipped.append(
                    f"  {contract.get('id', '?')} — no source_view defined"
                )
                continue

            if source_view not in existing_views:
                skipped.append(
                    f"  {contract.get('id', '?')} ({source_view}) — view not found in "
                    f"*consumption_views_{env}.sql"
                )
                continue

            covered.append(contract.get("id", source_view))

            qualified_view = f"{qualified_schema}.{source_view}"
            section: list[str] = []
            section.append(
                f"-- ── Contract: {contract.get('id', '')} v{contract.get('version', '')} ──"
            )

            # 1. COMMENT ON VIEW
            comment_text = _build_view_comment(contract)
            escaped_comment = _escape_sql_string(comment_text)
            section.append(
                f"COMMENT ON VIEW {qualified_view} IS\n"
                f"  '{escaped_comment}';"
            )

            # 2. SET TAGS
            cid = _escape_sql_string(str(contract.get("id", "")))
            cver = _escape_sql_string(str(contract.get("version", "")))
            grain_val = _escape_sql_string(str(contract.get("grain", "")))
            freshness = contract.get("freshness") or {}
            expected_min = str(freshness.get("expected_minutes", ""))
            section.append(
                f"ALTER VIEW {qualified_view} SET TAGS (\n"
                f"  'contract_id' = '{cid}',\n"
                f"  'contract_version' = '{cver}',\n"
                f"  'contract_grain' = '{grain_val}',\n"
                f"  'freshness_expected_minutes' = '{expected_min}'\n"
                f");"
            )

            # 3. COMMENT ON COLUMN (only fields that have a description)
            fields = contract.get("fields") or []
            col_comments: list[str] = []
            for field in fields:
                desc = field.get("description")
                if not desc:
                    continue
                fname = field.get("name", "")
                if not fname:
                    continue
                # Collapse multi-line YAML block scalars to a single line.
                desc_clean = re.sub(r"\s*\n\s*", " ", str(desc).strip())
                escaped_desc = _escape_sql_string(desc_clean)
                col_comments.append(
                    f"COMMENT ON COLUMN {qualified_view}.{fname} IS\n"
                    f"  '{escaped_desc}';"
                )
            if col_comments:
                section.extend(col_comments)
            else:
                section.append(
                    f"-- (no column descriptions in manifest for {source_view})"
                )

            body_parts.append("\n".join(section))

        # Build the file.
        header = HEADER_TEMPLATE.format(
            env_upper=env.upper(),
            env_lower=env,
            covered=len(covered),
            skipped=len(skipped),
            catalog=catalog,
            gold_schema=schema,
        )

        if skipped:
            skip_block = (
                "-- Skipped contracts (source_view not yet in consumption SQL):\n"
                + "\n".join(skipped)
                + "\n"
            )
        else:
            skip_block = "-- All contracts with a source_view are covered.\n"

        sql = header + skip_block + "\n" + "\n\n".join(body_parts) + "\n"

        out_path = base_dir / "resources" / "sql" / f"contract_metadata_{env}.sql"
        with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(sql)

        print(f"Generated: {out_path}  ({len(covered)} covered, {len(skipped)} skipped)")
        for s in skipped:
            print(f"  SKIPPED:{s}")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate Unity Catalog contract-metadata SQL (COMMENT ON VIEW, SET TAGS, COMMENT ON COLUMN)."
    )
    parser.add_argument(
        "--env",
        choices=list(ENVIRONMENTS),
        default=None,
        help="Restrict generation to one environment (default: all three).",
    )
    args = parser.parse_args(argv)
    generate_sql(env_filter=args.env)
    return 0


if __name__ == "__main__":
    sys.exit(main())
