-- Unity Catalog Access Grants (PROD).
--
-- Intentionally NO base-Gold grants. Per SECURITY.md, raw/Bronze/Silver/Gold base tables must never be
-- granted to the `users` consumer group: consumer access flows only through the governed
-- gold_io_reporting `*_secured` views (gold_security_prod.sql) and `vw_consumption_*` / `vw_genie_*` views.
--
-- Removed 2026-06-08 (SECURITY.md reconciliation): the prior
-- `GRANT SELECT ON TABLE connected_plant_prod.gold.gold_*readiness*/validation* TO `users`` statements.
-- They were both wrong and policy-violating:
--   (a) they targeted the `gold` schema, but the io-reporting readiness/validation tables are deployed to
--       `gold_io_reporting` (verified) — so the grants were dead (a GRANT on a non-existent table errors); and
--   (b) granting base Gold tables to `users` directly contradicts SECURITY.md.
-- Readiness/validation tables are NOT consumer-granted in the first wave. If a dashboard genuinely needs
-- one, add a `gold_io_reporting` `*_secured` view via scripts/generate_gold_security_sql.py and grant the
-- `*_secured` view — never the base table. Enforced by scripts/ci/check_gold_grants_policy.py.
