-- Unity Catalog base metadata — GOLD table annotations (UAT).
-- Generated by scripts/generate_base_metadata_sql.py — do not edit manually.
-- Run once as a UC admin after the DLT pipeline has created the tables.
-- Re-runnable: COMMENT ON and SET TAGS are idempotent (they overwrite existing values).
--
-- IMPORTANT: SET TAGS must be re-applied after any DLT full-refresh that re-creates the
-- table object (Databricks drops UC tags on table recreation).
--
-- Covers 97 table(s) across 12 metadata file(s).
-- Column comments are omitted where blank (P0 skeleton — populated in backfill phase).
--
-- UC syntax used:
--   COMMENT ON TABLE ... IS '...'          (table-level description, when non-empty)
--   ALTER TABLE ... SET TAGS (...)         (machine-readable governance tags)
--   COMMENT ON COLUMN ... IS '...'        (column-level descriptions, when non-empty)
--
-- Requires: APPLY TAG + MODIFY / OWNER on the target tables in connected_plant_uat.gold_io_reporting.

-- ── Table: gold_order_downtime_summary (from dlt_gold_pipeline.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_order_downtime_summary IS
  'Downtime events rolled to order × operation × reason grain with order context.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_order_downtime_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_order_downtime_summary — populate in backfill phase)

-- ── Table: gold_plant_production_quality_summary (from dlt_gold_pipeline.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_plant_production_quality_summary IS
  'Plant-level production quality & downtime summary.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_plant_production_quality_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_plant_production_quality_summary — populate in backfill phase)

-- ── Table: gold_process_order_component_status (from dlt_gold_pipeline.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_process_order_component_status IS
  'Per-component reservation status for active process orders with available stock coverage.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_process_order_component_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_process_order_component_status — populate in backfill phase)

-- ── Table: gold_process_order_operations (from dlt_gold_pipeline.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_process_order_operations IS
  'Operations Overview of process orders including schedule, confirmations, PI sheet, and downtime at operation grain.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_process_order_operations SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_process_order_operations — populate in backfill phase)

-- ── Table: gold_process_order_schedule_adherence (from dlt_gold_pipeline.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_process_order_schedule_adherence IS
  'Production order schedule-adherence metrics comparing scheduled vs actual completions.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_process_order_schedule_adherence SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_process_order_schedule_adherence — populate in backfill phase)

-- ── Table: gold_shift_output_summary (from dlt_gold_pipeline.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_shift_output_summary IS
  'Daily production output summary. Aggregates quantity and scrap by posting date and plant.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_shift_output_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_shift_output_summary — populate in backfill phase)

-- ── Table: gold_data_freshness_status (from freshness.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_data_freshness_status IS
  'Per-Silver-table replication freshness: lag vs SLA with FRESH/STALE/NO_DATA/STATIC status.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_data_freshness_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_data_freshness_status — populate in backfill phase)

-- ── Table: gold_data_health_summary (from freshness.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_data_health_summary IS
  'Gold observability rollup for freshness, expectations, config coverage, staging validation, and stock reconciliation health.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_data_health_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_data_health_summary — populate in backfill phase)

-- ── Table: gold_qm_characteristic_pareto (from quality_lab.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_qm_characteristic_pareto IS
  'QM characteristic (MIC) Pareto for the QM Command Centre drill view. Grain: plant_code × material_code × characteristic_id. Counts ALL lab results (not fails-only) from quality_lab_inspection_result over the qm_lookback_years silver window. Severity uses the shared _lab_result_severity_column rule with gold_qm_lab_result_signal. last_result_date is the per-plant×material freshness signal (max result_recording_start_date). Source-guarded when QM lab silver absent.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_qm_characteristic_pareto SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_qm_characteristic_pareto — populate in backfill phase)

-- ── Table: gold_qm_lab_result_signal (from quality_lab.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_qm_lab_result_signal IS
  'Lab Board result signal: one row per failed-or-warning QM inspection result in the recent window (lab_board_lookback_days, default 30d). Feeds the Connected Quality Lab Board wallboard (quality-batch-release workspace, lab-board view). Severity: ''fail''=outside spec; ''warn''=within warning band (explicit QAMV warning limits when available; 5%-of-span approximation otherwise). Only non-accepted results are included. Production line is left-joined via lot order number — nullable.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_qm_lab_result_signal SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_qm_lab_result_signal — populate in backfill phase)

-- ── Table: gold_qm_ud_code_pareto (from quality_lab.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_qm_ud_code_pareto IS
  'QM usage-decision code Pareto for the QM Command Centre drill view. Grain: plant_code × usage_decision_code. Plant attribution uses the parent lot plant (quality_inspection_usage_decision.plant_code from QALS.WERK gate — NOT QAVE.VWERKS). lot_count = distinct inspection lots per code; last_decision_date is the freshness signal. Source-guarded when QM UD silver absent.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_qm_ud_code_pareto SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_qm_ud_code_pareto — populate in backfill phase)

-- ── Table: gold_data_product_safety_status (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_data_product_safety_status IS
  'Safety classification of all conformed Gold data products.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_data_product_safety_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_data_product_safety_status — populate in backfill phase)

-- ── Table: gold_delivery_pick_status_validation (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_delivery_pick_status_validation IS
  'Validation check for mixed UoM delivery picking status.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_delivery_pick_status_validation SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_delivery_pick_status_validation — populate in backfill phase)

-- ── Table: gold_movement_type_classification_coverage (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_movement_type_classification_coverage IS
  'Validation check for movement type classification coverage.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_movement_type_classification_coverage SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_movement_type_classification_coverage — populate in backfill phase)

-- ── Table: gold_plant_freshness_readiness (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_plant_freshness_readiness IS
  'Validation check for plant replication freshness lag.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_plant_freshness_readiness SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_plant_freshness_readiness — populate in backfill phase)

-- ── Table: gold_plant_readiness_status (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_plant_readiness_status IS
  'Rollup readiness status and calculated score per plant, domain, and data product.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_plant_readiness_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_plant_readiness_status — populate in backfill phase)

-- ── Table: gold_readiness_dashboard_source (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_readiness_dashboard_source IS
  'Flattened reporting source optimized for plant readiness dashboards.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_readiness_dashboard_source SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_readiness_dashboard_source — populate in backfill phase)

-- ── Table: gold_recipe_line_enrichment_coverage (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_recipe_line_enrichment_coverage IS
  'Validation check for recipe process line enrichment coverage.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_recipe_line_enrichment_coverage SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_recipe_line_enrichment_coverage — populate in backfill phase)

-- ── Table: gold_stock_reconciliation_readiness (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_readiness IS
  'Validation check for stock reconciliation readiness.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_readiness SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_reconciliation_readiness — populate in backfill phase)

-- ── Table: gold_validation_failure_detail (from readiness_validation.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_validation_failure_detail IS
  'Actionable list of all validation checks and failure records.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_validation_failure_detail SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_validation_failure_detail — populate in backfill phase)

-- ── Table: gold_spc_quality_metric_subgroup (from spc_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_spc_quality_metric_subgroup IS
  'SPC subgroup MV — sample-grain rows from the quality result-grain silver (QASR per-sample means), enriched with lot context (QALS), spec limits / MIC metadata (QAMV), and material/plant names. Governed replacement for the legacy connected_plant_uat.gold.spc_quality_metric_subgroup_mv (decommissioned). Adapter-facing view: spc_quality_metric_subgroup_mv (see spc_serving_views_*.sql). Grain: one row per QASR sample (lot × operation × mic × sample_number). Subgroup key: plant_id × material_id × mic_id × operation_id × batch_id.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_spc_quality_metric_subgroup SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_spc_quality_metric_subgroup — populate in backfill phase)

-- ── Table: gold_batch_event_ledger (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_batch_event_ledger IS
  'Directional per-batch event ledger derived from gold_batch_lineage. One row per (batch × plant × direction) event, exploding each directed edge into per-batch rows so a single batch''s full movement history is queryable without graph traversal. DIRECTION SEMANTICS: PRODUCTION — parent side: OUT (batch consumed into child order); child side: IN (batch produced by the process order). STO_TRANSFER / BATCH_TRANSFER / MATERIAL_TRANSFER — parent side: OUT (batch sent); child side: IN (batch received). VENDOR_RECEIPT — child side only: IN (received from supplier; parent NULL). DELIVERY — parent side only: OUT (shipped to customer; child NULL). ADJUSTMENT_IN — child side: IN (stock write-on). ADJUSTMENT_OUT — parent side: OUT (stock write-off). COUNTERPART columns carry the opposite endpoint identity: COUNTERPART_MATERIAL_ID / COUNTERPART_BATCH_ID / COUNTERPART_PLANT_ID. VENDOR_RECEIPT IN rows: SUPPLIER_ID + PURCHASE_ORDER_ID populated. DELIVERY OUT rows: CUSTOMER_ID + DELIVERY_ID + SALES_ORDER_ID populated. PRODUCTION / TRANSFER rows: PROCESS_ORDER_ID + MATERIAL_DOCUMENT_NUMBER populated. Source: dlt.read(''gold_batch_lineage'') — intra-pipeline DLT dependency. Security: capability tier — NOT in GOLD_TABLES; GRANT added to resources/sql/trace_security_{env}.sql (traceability-readers group, tolerated failure). Grain: two rows per two-sided edge (OUT for parent, IN for child); one row per one-sided edge (VENDOR_RECEIPT IN only; DELIVERY OUT only). Phase 2 use cases: mass-balance timeline, supplier-batch panel, recall-readiness counts. Deterministic base (no current_date / current_timestamp).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_batch_event_ledger SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_batch_event_ledger — populate in backfill phase)

-- ── Table: gold_batch_lineage (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_batch_lineage IS
  'Governed batch traceability edge list — T2 of the Final Trace migration (ADR 016). One row per directed traceability edge: PARENT_* → CHILD_* with LINK_TYPE classifying the relationship. Five legs: PRODUCTION (CHVW × MSEG GR), STO/BATCH/MATERIAL_TRANSFER (CHVW receiving side), VENDOR_RECEIPT (MSEG PO receipt), DELIVERY (MSEG outbound issue), ADJUSTMENT_IN / ADJUSTMENT_OUT (MSEG stock adjustments). Lifecycle-gated: SOLD / DIVESTED_ON_SAP endpoint plants excluded (ADR 016 §2). Column names are the verbatim legacy contract (deliberate snake_case exception, ADR 016 §3). Security: capability-tier GRANT via trace_security_{env}.sql; no RLS row filter on the MV (T3 search views carry the per-user predicate). Grain: one edge per (parent_material × parent_batch × parent_plant × child_material × child_batch × child_plant × link_type × process_order_id × material_document_number). Deterministic base (no current_date / current_timestamp). NOTE: first materialisation requires a full gold pipeline run; parity check vs legacy link-type counts is the orchestrator''s post-rollout step.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_batch_lineage SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_batch_lineage — populate in backfill phase)

-- ── Table: gold_batch_stock_summary (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_batch_stock_summary IS
  'Batch-grain stock position from silver.batch_stock (MCHB-derived). One row per (plant_code, material_code, batch_number) with the six SAP stock-category quantities: unrestricted, quality_inspection, blocked, restricted_use, in_transfer, blocked_returns — plus total_quantity (sum of all categories) and base_unit_of_measure. Source: silver.batch_stock (plant-gated current-state MCHB snapshot; one row per material × plant × storage_location × batch). Grain: this MV aggregates across storage locations, collapsing to the batch level so each (plant_code, material_code, batch_number) appears once. Use case: batch-level stock position for the trace2 fan-out — the Phase 2 recall-readiness and mass-balance panels need a governed batch-stock position rather than the ungated legacy gold_batch_stock_v. Standard plant RLS: expose plant_code; governed via gold_batch_stock_summary_secured (scripts/generate_gold_security_sql.py GOLD_TABLES). NOTE: quantities are summed across all storage locations for a given plant/material/batch. Phase 2 consumers requiring storage-location granularity should read silver.batch_stock. Deterministic base (no current_date / current_timestamp).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_batch_stock_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_batch_stock_summary — populate in backfill phase)

-- ── Table: gold_trace_anchor (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_anchor IS
  'Governed batch traceability anchor index — T3 of the Final Trace migration (ADR 016). One row per (MATERIAL_ID, BATCH_ID, PLANT_ID) entry point that a user may initiate a trace from. Built by unioning the parent and child endpoint sides of gold_batch_lineage and aggregating to a batch-plant grain with date-range and directional edge counts. ANCHORABILITY GATE (ADR 016 §3): only plants with effective_lifecycle = ''ACTIVE'' are retained. This is deliberately the OPPOSITE default from the edge MV''s keep-unknowns policy — edges keep unknown plants for graph continuity (ADR 016 §2 pass-through), but anchors require explicit ACTIVE because a trace may only be INITIATED from a reviewed- active plant; CLOSED and unconfirmed-review plants are traversable but not anchorable. Null/blank BATCH_ID rows are excluded (an anchor is a batch-level entry point). Null PLANT_ID rows are excluded (RLS predicate cannot apply to a null plant). plant_code = PLANT_ID (lowercase contract column for the RLS predicate). Security: ADDED to generate_gold_security_sql.py GOLD_TABLES — served via gold_trace_anchor_secured with standard plant_code CSM predicate (application_key = ''io_reporting''). Deterministic base (no current_date / current_timestamp). NOTE: app batch-search switchover from the legacy search surface to this anchor tier is a separate follow-up task.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_trace_anchor SET TAGS (
  'layer' = 'gold',
  'product_area' = 'traceability'
);
-- (no column comments yet for gold_trace_anchor — populate in backfill phase)

-- ── Table: gold_trace_batch_material (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_batch_material IS
  'Batch–supplier-batch linkage for traceability fan-out: (material_code, batch_number) → SUPPLIER_BATCH_ID (vendor''s own batch identifier). Source: silver.batch_where_used (CHVW), which carries LICHA (vendor batch) on rows where a batch was received from a supplier (LICHA populated on VENDOR_RECEIPT rows). SOURCE DECISION — MCH1/MCHA NOT used: SAP MCH1 (client-level batch master, material + batch grain, carries LICHA/MFRGR/VFDAT) and MCHA (plant-level batch, carries LICHA) are listed in the data dictionary but are NOT replicated into the connected_plant.sap source schema (no bronze table batchmaster_mch1 or equivalent exists — confirmed by absence of any MCH1/MCHA reference in pipeline code outside of generate_data_dictionary.py). An ingestion request for MCH1 would unlock manufacture_date (MFRGR) and expiry_date (VFDAT) which are also missing from the governed stack; raise as a follow-up ingestion request. CHVW.LICHA IS available (confirmed in silver/tables/traceability.py, _CHVW_REQUIRED list, line 62) and is already surfaced in silver.batch_where_used.vendor_batch_number. GRAIN: one row per (material_code, batch_number) — SUPPLIER_BATCH_ID deduplicated with F.max (a batch has at most one supplier batch reference; max() is a stable tiebreak in the rare case LICHA changes across CHVW rows for the same batch). NULL / blank LICHA rows are excluded (no vendor batch = no useful linkage). Legacy contract target: gold_batch_material — MATERIAL_ID, BATCH_ID, SUPPLIER_BATCH_ID. Security: capability tier — NOT in GOLD_TABLES; GRANT added to resources/sql/trace_security_{env}.sql (traceability-readers group, tolerated failure). NOTE: silver.batch_where_used is built by the slow reference pipeline (estate-wide CHVW snapshot). This gold MV reads it via spark.read.table (cross-pipeline Delta read). Deterministic base (no current_date / current_timestamp).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_trace_batch_material SET TAGS (
  'layer' = 'gold',
  'product_area' = 'traceability'
);
-- (no column comments yet for gold_trace_batch_material — populate in backfill phase)

-- ── Table: gold_trace_material (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_material IS
  'Material lookup for traceability fan-out: material_code → material_description, material_type, material_group, base_uom. Source: silver.material (MARA + MARC + MAKT, plant-scoped). GRAIN DECISION: silver.material is one row per (plant_code, material_code) because MARA attributes live on MARC/plant rows. This MV aggregates across plants using F.max (deterministic — same description for a given material_code regardless of plant; max() is a stable tiebreak that avoids arbitrary ordering). One row per material_code. LANGUAGE: silver.material is pre-filtered to MAKT.SPRAS=''E'' (English) in reference.py — all rows are English; the LANGUAGE_ID=''E'' convention from legacy gold_material is preserved as a literal column so adapter SQL can JOIN on LANGUAGE_ID = ''E'' unchanged. CONSUMER GRAIN: trace2 adapters join on MATERIAL_ID only (no plant), matching the plant-independent grain produced here. The legacy gold_material carried one row per (MATERIAL_ID) with a LANGUAGE_ID column — this MV matches that contract. Security: capability tier — NOT in GOLD_TABLES; GRANT added to resources/sql/trace_security_{env}.sql (traceability-readers group, tolerated failure). NOTE: silver.material is built by the slow reference pipeline. This gold MV reads it via spark.read.table (cross-pipeline Delta read). Deterministic base (no current_date / current_timestamp).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_trace_material SET TAGS (
  'layer' = 'gold',
  'product_area' = 'traceability'
);
-- (no column comments yet for gold_trace_material — populate in backfill phase)

-- ── Table: gold_trace_plant (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_plant IS
  'Plant lookup for traceability fan-out: plant_code → plant_name, country_key. Source decision: silver.plant (T001W via published central_services) UNION silver.site_lifecycle (estate-wide ~550-plant dimension, ADR 016). silver.plant covers actively-replicated plants; site_lifecycle fills in estate plants not yet in T001W (e.g. plants reviewed as CLOSED/SOLD that are in the traceability graph but not in the live plant master). Per-side dedup then FULL OUTER join with F.coalesce — silver.plant (T001W) values are preferred wherever both sources carry the plant; site_lifecycle fills estate-only plants. silver.site_lifecycle.country maps to country_key (same attribute, different column name). GRAIN: one row per plant_code (F.max tiebreak for determinism). CONSUMER GRAIN: trace2 adapters join on PLANT_ID only, matching this grain. Legacy contract target: gold_plant — PLANT_ID, PLANT_NAME (adapters reference p.PLANT_ID, p.PLANT_NAME). Security: capability tier — NOT in GOLD_TABLES; GRANT added to resources/sql/trace_security_{env}.sql (traceability-readers group, tolerated failure). NOTE: silver.plant and silver.site_lifecycle are built by the slow reference pipeline. This gold MV reads them via spark.read.table (cross-pipeline Delta reads). Deterministic base (no current_date / current_timestamp).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_trace_plant SET TAGS (
  'layer' = 'gold',
  'product_area' = 'traceability'
);
-- (no column comments yet for gold_trace_plant — populate in backfill phase)

-- ── Table: gold_trace_vendor (from trace_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_vendor IS
  'Vendor lookup for traceability fan-out: vendor_code → vendor_name, country_key. Source: silver.vendor (LFA1 via published_<env>.central_services.vendormaster_lfa1). One row per vendor_code. Vendor names are used in the Phase 2 supplier-batch panel to resolve SUPPLIER_ID → display name without a per-query join to the heavy LFA1 table. SUPPLIER_ID in gold_batch_lineage / gold_batch_event_ledger is the vendor_code from silver.purchase_order (EKKO.LIFNR → vendor_code after strip_zeros), which matches the vendor_code PK of silver.vendor. Grain: one row per vendor_code (deduped). Security: capability tier — NOT in GOLD_TABLES; GRANT added to resources/sql/trace_security_{env}.sql (traceability-readers group, tolerated failure). NOTE: silver.vendor is built by the slow reference pipeline. This gold MV reads it via spark.read.table (cross-pipeline Delta read). Deterministic base (no current_date / current_timestamp).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_trace_vendor SET TAGS (
  'layer' = 'gold',
  'product_area' = 'traceability'
);
-- (no column comments yet for gold_trace_vendor — populate in backfill phase)

-- ── Table: gold_warehouse_exceptions (from warehouse_exceptions.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_warehouse_exceptions IS
  'Warehouse data-integrity and aging exception CANDIDATES with severity (1-4) and SLA " "hours. Age thresholds are applied at query time by gold_warehouse_exceptions_live " "(base MV is deterministic — read the _live view for confirmed exceptions).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_warehouse_exceptions SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_warehouse_exceptions — populate in backfill phase)

-- ── Table: gold_delivery_pick_status (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_delivery_pick_status IS
  'OUTBOUND delivery pick progress (picked vs delivery quantity) by delivery. Filtered to non-inbound document types (delivery_type NOT IN (''EL'',''ELST'')) using LFART as an interim direction proxy — verified against UAT type mix 2026-06-11. Row counts dropped ~65% vs the prior unfiltered version; that is the fix, not a regression. See gold_wm_inbound_deliveries for EL/ELST inbound counterpart.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_delivery_pick_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_delivery_pick_status — populate in backfill phase)

-- ── Table: gold_dispensary_backlog (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_dispensary_backlog IS
  'Open dispensary / line-pick backlog by plant and supply area, using movement_type_classification.is_production_consumption.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_dispensary_backlog SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_dispensary_backlog — populate in backfill phase)

-- ── Table: gold_goods_movement_activity (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_goods_movement_activity IS
  'Goods-movement activity feed at MSEG-line grain (IM postings joined to the movement-type classification). High-volume table: consumers MUST filter on a bounded posting_date window — the serving route enforces a default 1-day window and a hard 31-day maximum (see plan section 5, cost controls).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_goods_movement_activity SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_goods_movement_activity — populate in backfill phase)

-- ── Table: gold_hu_reconciliation (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_hu_reconciliation IS
  'Handling-unit packed quantity reconciled to WM quant stock by plant × warehouse × material × batch. Supports HU/batch traceability checks.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_hu_reconciliation SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_hu_reconciliation — populate in backfill phase)

-- ── Table: gold_lineside_stock (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_lineside_stock IS
  'Current stock staged in production / line-side storage types, by material and batch.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_lineside_stock SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_lineside_stock — populate in backfill phase)

-- ── Table: gold_movement_reconciliation (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_movement_reconciliation IS
  'IM goods movement postings reconciled to WM confirmed transfer-order activity by plant × warehouse × posting/confirmation date × material × batch.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_movement_reconciliation SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_movement_reconciliation — populate in backfill phase)

-- ── Table: gold_physical_inventory_recon (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_physical_inventory_recon IS
  'Physical inventory count-vs-book reconciliation from IKPF/ISEG, including difference posting and material-document evidence.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_physical_inventory_recon SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_physical_inventory_recon — populate in backfill phase)

-- ── Table: gold_process_order_staging (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_process_order_staging IS
  'Process-order component staging completion (confirmed transfer orders vs total) per order.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_process_order_staging SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_process_order_staging — populate in backfill phase)

-- ── Table: gold_process_order_staging_validation (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_process_order_staging_validation IS
  'Per-plant/warehouse validation of the LTAK BETYP=''F'' source-reference assumption used by gold_process_order_staging. Classifies each plant/warehouse as VALIDATED (>=95% BENUM matches a known process order), NOT_VALIDATED (F-type TOs present but low match rate), or NOT_APPLICABLE (no F-type staging TOs for this plant/warehouse).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_process_order_staging_validation SET TAGS (
  'layer' = 'gold',
  'product_area' = 'process_order'
);
-- (no column comments yet for gold_process_order_staging_validation — populate in backfill phase)

-- ── Table: gold_reconciliation_alerts (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_reconciliation_alerts IS
  'Alert-ready reconciliation exceptions for severe IM↔WM, HU, movement, and physical inventory variances.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_reconciliation_alerts SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_reconciliation_alerts — populate in backfill phase)

-- ── Table: gold_reconciliation_audit_log (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_reconciliation_audit_log IS
  'Current-state audit register for reconciliation exceptions. Append-only trend history is captured by the warehouse snapshot job.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_reconciliation_audit_log SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_reconciliation_audit_log — populate in backfill phase)

-- ── Table: gold_stock_holds (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_holds IS
  'Current quant-level holds (Quality, Blocked, Restricted) in WM.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_holds SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_holds — populate in backfill phase)

-- ── Table: gold_stock_reconciliation (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation IS
  'IM book stock (MARD) vs WM bin stock variance, with valuation, ABC class, and interim stock split, by plant and material.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_reconciliation — populate in backfill phase)

-- ── Table: gold_stock_reconciliation_exceptions_v2 (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_exceptions_v2 IS
  'Non-reconciled rows from gold_stock_reconciliation_v2, enriched with material description. Use as the starting point for variance investigation.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_exceptions_v2 SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_reconciliation_exceptions_v2 — populate in backfill phase)

-- ── Table: gold_stock_reconciliation_summary (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_summary IS
  'Canonical summary of IM↔WM stock reconciliation by plant × warehouse × mismatch reason. Backed by gold_stock_reconciliation_v2.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_reconciliation_summary — populate in backfill phase)

-- ── Table: gold_stock_reconciliation_summary_v2 (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_summary_v2 IS
  'Summary of gold_stock_reconciliation_v2 rolled up by plant × warehouse × mismatch_reason × mismatch_severity.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_summary_v2 SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_reconciliation_summary_v2 — populate in backfill phase)

-- ── Table: gold_stock_reconciliation_v2 (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_v2 IS
  'Detailed IM↔WM stock reconciliation at plant × warehouse × material × batch × stock_category grain. Compares MCHB/MARD (IM) with LQUA/storage_bin (WM). See docs/reconciliation/stock-reconciliation-v2-contract.md.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_reconciliation_v2 SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_reconciliation_v2 — populate in backfill phase)

-- ── Table: gold_stock_value_reconciliation (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_value_reconciliation IS
  'Value-control rollup of IM↔WM reconciliation v2 by plant × warehouse × mismatch reason. Uses material valuation where available.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_value_reconciliation SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_value_reconciliation — populate in backfill phase)

-- ── Table: gold_storage_type_role_coverage_status (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_storage_type_role_coverage_status IS
  'Per-plant/warehouse coverage of storage_type_role_mapping config vs in-use storage types. VALIDATED = all active storage types are config-mapped; PARTIAL = some mapped, some not; MISSING = no config rows for this warehouse. Use to identify gaps before relying on gold_lineside_stock or gold_stock_reconciliation for a plant/warehouse.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_storage_type_role_coverage_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_storage_type_role_coverage_status — populate in backfill phase)

-- ── Table: gold_transfer_order_open_items (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_transfer_order_open_items IS
  'Current open transfer-order items (pick tasks).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_transfer_order_open_items SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_transfer_order_open_items — populate in backfill phase)

-- ── Table: gold_transfer_requirement_open_items (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_transfer_requirement_open_items IS
  'Current open transfer-requirement items (move requests).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_transfer_requirement_open_items SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_transfer_requirement_open_items — populate in backfill phase)

-- ── Table: gold_wm_inbound_deliveries (from warehouse_flow_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_inbound_deliveries IS
  'Inbound deliveries (LFART EL=standard inbound, ELST=inbound stock transport) with expected receipt date (LIKP.WADAT renamed), line counts, delivery quantity, pick/GR progress, and status rollup. Sourced from gold_delivery_pick_status''s counterpart (the EL/ELST subset of silver.outbound_delivery). Vendor/partner columns are not available in silver.outbound_delivery (ship_to/sold_to are SAP customer fields on LIKP; inbound deliveries carry the supplier via a different field not currently replicated). Verified against UAT type mix 2026-06-11: EL=178,632 ELST=2,651.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_inbound_deliveries SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_inbound_deliveries — populate in backfill phase)

-- ── Table: gold_handling_unit_summary (from warehouse_inbound_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_handling_unit_summary IS
  'Handling-unit (SSCC) summary by plant, warehouse and status.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_handling_unit_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'ioreporting'
);
-- (no column comments yet for gold_handling_unit_summary — populate in backfill phase)

-- ── Table: gold_inbound_po_backlog (from warehouse_inbound_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_inbound_po_backlog IS
  'Open inbound purchase-order backlog (PO items awaiting goods receipt) by plant and " "vendor. Backlog only — does NOT use GR history / remaining quantity (see design_spec).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_inbound_po_backlog SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_inbound_po_backlog — populate in backfill phase)

-- ── Table: gold_inbound_po_backlog_enhanced (from warehouse_inbound_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_inbound_po_backlog_enhanced IS
  'Enhanced open inbound purchase-order backlog by plant and vendor, including PO-linked 103/104 goods-receipt quantity, remaining open quantity, putaway TO evidence, and age anchors.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_inbound_po_backlog_enhanced SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_inbound_po_backlog_enhanced — populate in backfill phase)

-- ── Table: gold_inbound_po_line_backlog (from warehouse_inbound_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_inbound_po_line_backlog IS
  'Open inbound purchase-order backlog at PO-LINE grain (one row per plant x PO x item; items " "not delivery-complete and not deleted). First-wave core EKKO/EKPO fields + material name; " "GR/open quantity, delivery date, QA status, vendor name are future enrichment (design_spec).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_inbound_po_line_backlog SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_inbound_po_line_backlog — populate in backfill phase)

-- ── Table: gold_warehouse_kpi_snapshot (from warehouse_kpi_snapshot.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_warehouse_kpi_snapshot IS
  'Per-plant warehouse operations scorecard (open orders, TRs, TOs, deliveries, inbound, bins).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_warehouse_kpi_snapshot SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_warehouse_kpi_snapshot — populate in backfill phase)

-- ── Table: gold_bin_occupancy (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_bin_occupancy IS
  'Current warehouse bin occupancy by warehouse, plant, storage type, and bin type.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_bin_occupancy SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_bin_occupancy — populate in backfill phase)

-- ── Table: gold_inbound_outbound_throughput (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_inbound_outbound_throughput IS
  'Inbound, outbound, transfer, and adjustment throughput by plant, storage location, and date.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_inbound_outbound_throughput SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_inbound_outbound_throughput — populate in backfill phase)

-- ── Table: gold_stock_availability (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_availability IS
  'Current stock availability by plant, storage location, material, batch, and base UOM.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_availability SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_availability — populate in backfill phase)

-- ── Table: gold_stock_expiry_risk (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_stock_expiry_risk IS
  'Current batch stock expiry risk by plant, material, batch, and base UOM.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_stock_expiry_risk SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_stock_expiry_risk — populate in backfill phase)

-- ── Table: gold_transfer_order_performance (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_transfer_order_performance IS
  'Transfer-order operator performance by warehouse, plant, date, and source storage type.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_transfer_order_performance SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_transfer_order_performance — populate in backfill phase)

-- ── Table: gold_transfer_requirement_backlog (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_transfer_requirement_backlog IS
  'Current open transfer-requirement backlog by warehouse, plant, queue, and source/destination storage.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_transfer_requirement_backlog SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_transfer_requirement_backlog — populate in backfill phase)

-- ── Table: gold_transfer_requirement_material_backlog (from warehouse_kpis.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_transfer_requirement_material_backlog IS
  'Open transfer-requirement backlog aggregated to plant x material — material-level shortfall " "for the Warehouse360 shortfalls governed view (ADR-0004 D2). Open = not processing-complete " "with open_quantity > 0. Aggregated across warehouses/queues to the contract''s plant x material grain.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_transfer_requirement_material_backlog SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_transfer_requirement_material_backlog — populate in backfill phase)

-- ── Table: gold_wm_adherence_root_cause (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_adherence_root_cause IS
  'Order-grain adherence miss root-cause classification for Production Progress. One row per candidate miss (plant_code × order_number): scheduled_finish_date present AND (actual_finish_date > scheduled_finish_date OR actual_finish_date IS NULL for open-late candidates — consumption view derives is_open_late via CURRENT_DATE). Classification precedence (first match wins): 1 LATE_RELEASE — actual_release_date > scheduled_start_date; 2 MATERIAL_SHORT — any gold_wm_order_component_variance row with variance_qty < -{_MATERIAL_SHORT_TOLERANCE}; 3 CAPACITY — not late release, no material short, but production_first_actual_start is >24h after actual_release_date (gold_wm_order_journey_summary); 4 UNCLASSIFIED. Evidence columns retained for UI drill-down. Deterministic: no current_date(). cluster_by plant_code, scheduled_finish_date.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_adherence_root_cause SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_adherence_root_cause — populate in backfill phase)

-- ── Table: gold_wm_bin_stock_detail (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_bin_stock_detail IS
  'Quant-grain stock & bin explorer: every occupied bin with storage-zone classification (dispensary / production supply / palletising / interim / warehouse), stock category, block flags and expiry. The dispensary stock-health view is this table filtered to storage_zone = ''DISPENSARY''. Empty bins are excluded (bin-capacity views are served by gold_bin_occupancy).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_bin_stock_detail SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_bin_stock_detail — populate in backfill phase)

-- ── Table: gold_wm_campaign_summary (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_campaign_summary IS
  'Campaign-grouped picking progress (LTBK ZZ_CAMPAIGN — WMA-E-29/50 shared-material campaign picking): TR/status counts, orders covered, operators, quantities.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_campaign_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_campaign_summary — populate in backfill phase)

-- ── Table: gold_wm_daily_activity (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_daily_activity IS
  'Daily warehouse activity series per plant: TO items confirmed, TRs created, and IM goods receipts/issues. Deterministic facts (no snapshots) for trend charts.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_daily_activity SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_daily_activity — populate in backfill phase)

-- ── Table: gold_wm_daily_activity_baseline (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_daily_activity_baseline IS
  'Day-of-week baseline bands for daily warehouse activity metrics per plant. Grain: one row per plant_code × metric_name × day_of_week (1=Sun … 7=Sat). Computed via unpivot of gold_wm_daily_activity then percentile_approx groupBy. Partial-day exclusion is query-time (consumption view filters activity_date < CURRENT_DATE()); all rows present in gold_wm_daily_activity are included here (SAP extracts are closed daily). No current_date()/current_timestamp() — deterministic base MV.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_daily_activity_baseline SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_daily_activity_baseline — populate in backfill phase)

-- ── Table: gold_wm_downtime_event_detail (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_downtime_event_detail IS
  'Production downtime events at event grain — passthrough of the key columns from silver.downtime_event for drill-through in the Production Health view. Feeds the recent-events table and order-number drill-through.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_downtime_event_detail SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_downtime_event_detail — populate in backfill phase)

-- ── Table: gold_wm_downtime_pareto (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_downtime_pareto IS
  'Weekly production downtime pareto: plant_code × week_start × downtime_reason_code × sub_reason_code × work_centre_code grain. week_start = date_trunc(''week'', start_datetime) cast to DATE. Aggregates event_count, total/avg duration, and distinct order count. Rows with NULL start_datetime are excluded. Feeds the Production Health view.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_downtime_pareto SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_downtime_pareto — populate in backfill phase)

-- ── Table: gold_wm_expiry_risk (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_expiry_risk IS
  'Plant/material/batch shelf-life risk from plant-scoped MCHB batch stock enriched with client-level MCH1 batch master expiry/manufacture dates and MBEW valuation. Gold carries deterministic expiry_date only; days_to_expiry and expiry bands are computed in the consumption view. FEFO v1 flags later-expiring stocked batches that have issue evidence (261/601) while an earlier-expiring batch for the same plant/material remains on hand.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_expiry_risk SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_expiry_risk — populate in backfill phase)

-- ── Table: gold_wm_lineside_lines (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_lineside_lines IS
  'Distinct production lines with active order count — line picker for the Lineside Monitor config panel. Grain: plant_code × production_line. active_order_count: COUNT of running orders (released, not finished, not closed). line_label: production_line_description (first non-null) or production_line when no description is available. Source: process_order (production_line, production_line_description — CRVER/recipe classification). Deterministic: no current_date(). cluster_by plant_code.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_lineside_lines SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_lineside_lines — populate in backfill phase)

-- ── Table: gold_wm_lineside_now (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_lineside_now IS
  'Running orders + current-phase surface for the Lineside Monitor wall display. Grain: plant_code × production_line × order_number — one row per order currently in execution (released by date-evidence, actual_finish_date IS NULL, has at least one confirmed operation OR confirmed_yield_quantity > 0). current_operation_number / current_operation_description / current_activity_type: derived from the latest is_confirmed process_order_operation row (OPERATION_CONFIRMED logic — same pattern as gold_wm_order_journey_events). pct_complete: yield_pct from gold_wm_order_yield via dlt.read, clamped 0–100. planned_minutes: scheduled_finish_datetime − scheduled_start_datetime in minutes (integer — datediff of timestamps). production_first_actual_start: carried from process_order.actual_start_date cast as timestamp (wall-clock elapsed computed AT QUERY TIME in _live / consumption view). batch: single batch_number where exactly one distinct non-null batch is confirmed across operations; null when multiple batches or none. elapsed_minutes and projected_finish are NOT in this MV — they are computed in the consumption view using CURRENT_TIMESTAMP() (ADR 012 wall-clock rule). Deterministic: no current_date()/current_timestamp(). cluster_by plant_code, production_line.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_lineside_now SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_lineside_now — populate in backfill phase)

-- ── Table: gold_wm_operator_activity (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_operator_activity IS
  'RF operator pick activity at plant x warehouse x operator x confirmation-date grain, from confirmed transfer-order items (LTAP QNAME/QDATU). Quantity totals mix base UoMs — item counts are the comparable measure.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_operator_activity SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_operator_activity — populate in backfill phase)

-- ── Table: gold_wm_order_component_detail (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_component_detail IS
  'Component-level staging detail for active process orders — the drill-through behind Order Readiness. One row per component reservation with material-level TR coverage (LTBK BETYP=''P''), staging-TO pick progress (LTAK BETYP=''F''), and order-keyed PSA bin supply. TR/TO/PSA rollups are at order x material grain (silver TR items do not carry RSPOS), so components sharing a material show the same pool — flagged via material_component_count.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_component_detail SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_component_detail — populate in backfill phase)

-- ── Table: gold_wm_order_component_variance (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_component_variance IS
  'Order + material grain material variance for the Yield & Loss analytics waterfall. One row per plant_code × order_number × material_code. Sources: reservation_requirement (RESB) aggregated to order+material grain (sum required_quantity, sum withdrawn_quantity per order+material) then joined to goods_movement net issues (261 minus 262 per order+material). Silver goods_movement carries no reservation references (MSEG has no RSNUM/RSPOS mapping in the replication schema), so joining at reservation grain would double-count issued_qty when an order has multiple RESB rows for the same material. Quantities stay in each row''s own base_uom — no cross-material aggregation. est_loss_value: (issued_qty - required_qty) × standard_price / price_unit from material_valuation (same source as gold_wm_slow_movers / gold_wm_qm_disposition_queue). NULL when standard_price is absent. Deletion-flagged and zero-required-qty reservations are excluded. No current_date()/current_timestamp() — deterministic base MV. cluster_by plant_code, order_number.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_component_variance SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_component_variance — populate in backfill phase)

-- ── Table: gold_wm_order_journey_events (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_journey_events IS
  'Long-format per-order event timeline for the Order Journey Timeline view -- one row per event, identified by (plant_code, order_number, event_seq). Sources UNION ALL: ORDER_CREATED / RELEASED from process_order; TR_CREATED from warehouse_transfer_requirement (BETYP=''P''); STAGING_CONFIRMED from warehouse_transfer_order items (Fully Confirmed, via TBNUM->BETYP=''P'' TR chain); PI_START / PI_END from pi_sheet_execution (left/optional); OPERATION_CONFIRMED from process_order_operation (is_confirmed=true); GR_POSTED from goods_movement (movement_type 101 by order_number); COMPONENT_ISSUED from goods_movement (261 family); QM_LOT_CREATED / QM_UD_TAKEN from quality_inspection_lot + usage decision (source-guarded). event_seq = row_number over event_ts NULLS LAST within plant_code x order_number. Deterministic: no current_date(). cluster_by plant_code x order_number.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_journey_events SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_journey_events — populate in backfill phase)

-- ── Table: gold_wm_order_journey_summary (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_journey_summary IS
  'Per-order milestone summary for the Order Journey Timeline view -- one row per plant_code x order_number. Milestones from five sources joined by order_number: process_order (created/release/scheduled dates, production_line, material), warehouse_transfer_requirement (staging: first TR created ts, first/last staging confirmed ts, item counts via TBNUM linkage), process_order_operation (production actual start/finish, confirmed yield/scrap), pi_sheet_execution (PI first/last activity -- absent at P806; left join, nullable), goods_movement (GR from 101 by order_number, GI/issue qty from 261 family, delivery_count from delivery_number where present). Derived lag columns only where both endpoints exist. Deterministic: no current_date(). cluster_by plant_code x scheduled_start_date.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_journey_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_journey_summary — populate in backfill phase)

-- ── Table: gold_wm_order_operations (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_operations IS
  'Process-order operations enriched with work-centre description — one row per plant_code × order_number × routing_number × operation_counter. Drill-through behind the Order Detail overlay (Item B): operation sequence, scheduled window, actual start, yield, scrap, and derived completion status. LEFT JOIN to work_centre on work_centre_internal_id + plant_code.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_operations SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_operations — populate in backfill phase)

-- ── Table: gold_wm_order_readiness (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_readiness IS
  'Released process orders with derived TR coverage (component demand converted to transfer requirements — the WM Cockpit ''TR'' status) and PSA supply status (stock in order-keyed Production Supply bins vs WM component demand — the cockpit ''ST'' status). Coverage denominators use WM-managed components only (RESB rows carrying a warehouse number); quantity comparisons assume base-UoM consistency and are approximate for mixed-UoM orders.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_readiness SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_readiness — populate in backfill phase)

-- ── Table: gold_wm_order_shortage_projection (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_shortage_projection IS
  'Open order-component shortage projection for the Shortage Projection board. Grain: plant_code × order_number × material_code × reservation (one row per open component demand). Scope: active open orders (released by date-evidence, not finished). projected_balance_at_demand = ledger balance_before at the component requirement_date; is_projected_short when balance_before < open quantity. first_short_date = earliest ledger event_date where running_balance < 0 for that plant×material. Deterministic: no current_date(). cluster_by plant_code, requirement_date.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_shortage_projection SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_shortage_projection — populate in backfill phase)

-- ── Table: gold_wm_order_wip_stage (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_wip_stage IS
  'Active process order WIP stage — one row per plant_code × order_number for orders that are released but not yet finished (the same active-order filter as gold_wm_order_readiness). Stage is derived deterministically from the milestone columns in gold_wm_order_journey_summary (joined by plant_code × order_number): RELEASED (released, no TR created yet), STAGING (first TR exists, staging_last_confirmed_ts < staging_first_confirmed_ts — i.e. staging is in progress but not yet complete across all TRs), STAGED (staging_last_confirmed_ts present, no production start yet), IN_PRODUCTION (production_first_actual_start present, no GR posted), GR_PARTIAL (first_gr_posting_date present, gr_qty < order_qty × _COVERAGE_FULL_FRACTION), GR_COMPLETE (gr_qty >= order_qty × _COVERAGE_FULL_FRACTION). Includes order qty, material, scheduled dates. No current_date/current_timestamp. cluster_by plant_code.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_wip_stage SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_wip_stage — populate in backfill phase)

-- ── Table: gold_wm_order_yield (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_yield IS
  'Order-grain yield summary for the Yield & Loss analytics view. One row per plant_code × order_number. Sources: process_order (planned qty, status, dates, production_line) and goods_movement (net GR: movement 101 minus 102 per order). planned_qty = order_quantity (AFKO.GAMNG). delivered_qty = sum of movement-101 quantities minus movement-102 quantities for the same order, null-safe. yield_pct = delivered_qty / planned_qty (guarded for null/zero planned_qty). has_goods_receipt = delivered_qty > 0. is_complete = actual_finish_date IS NOT NULL. first/last_gr_date from goods_movement posting_date. No current_date()/current_timestamp() — deterministic base MV. cluster_by plant_code, scheduled_finish_date.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_order_yield SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_order_yield — populate in backfill phase)

-- ── Table: gold_wm_pi_accuracy (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_pi_accuracy IS
  'Physical-inventory count accuracy KPIs aggregated to plant × storage_location_code × cycle_counting_indicator (ABC class) × count_month grain. Source: gold_physical_inventory_recon via dlt.read — no current_date(); deterministic base MV. count_month = date_trunc(''month'', count_date). ''due_lines'' = all PI document lines in the period (documents created/counted in that month, regardless of status) — honest denominator for coverage; recounts are counted as distinct lines as they appear in ISEG. storage_zone is intentionally null: IKPF/ISEG carry only storage_location_code (LGORT), not storage_type, so a clean join to storage_type_role_mapping is not possible. Best-effort grouping by storage_location_code is preserved; a future enhancement can add LGORT→LGTYP mapping once it is replicated. delta_value is local currency — do not sum across currencies; currency is surfaced and grouped so cross-currency aggregation is an explicit consumer choice. count_accuracy_pct and coverage_pct are query-time ratios computed here at the per-group level only (deterministic within the group). cluster_by plant_code, count_month.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_pi_accuracy SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_pi_accuracy — populate in backfill phase)

-- ── Table: gold_wm_qm_disposition_queue (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_qm_disposition_queue IS
  'QM disposition queue — open lots only (no usage decision). Enriched with blocked stock quantity (quality_inspection_quantity from batch_stock, the MCHB.CINSM field) and estimated blocked value (blocked_qty × standard_price / price_unit from material_valuation). Grain: plant_code × inspection_lot_number. Date-relative columns (lot_age_days, is_overdue) live in the qm_disposition_queue_live serving view.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_qm_disposition_queue SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_wm_qm_disposition_queue — populate in backfill phase)

-- ── Table: gold_wm_qm_lot_context (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_qm_lot_context IS
  'Quality inspection-lot context per plant x material x batch: open (no usage decision yet) lot counts and the latest decision from the 1:many QAVE child table. Joined client-side onto Stock Health held stock and Inbound to answer ''why is this batch in QI and when is the UD due''. Covers the silver QM lookback window only.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_qm_lot_context SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_wm_qm_lot_context — populate in backfill phase)

-- ── Table: gold_wm_qm_lot_status (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_qm_lot_status IS
  'QM inspection lot status — one row per plant_code × inspection_lot_number (all lots in the silver lookback window). Carries lot header fields, material name from the material lookup, and the latest usage decision (collapsed from the 1:many QAVE child via max_by date+counter). Date-relative columns (lot_age_days, ud_lead_time_days, is_overdue) live in the qm_lot_status_live serving view (no current_date() here).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_qm_lot_status SET TAGS (
  'layer' = 'gold',
  'product_area' = 'spc'
);
-- (no column comments yet for gold_wm_qm_lot_status — populate in backfill phase)

-- ── Table: gold_wm_queue_workload (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_queue_workload IS
  'Current open WM workload by plant x warehouse x queue x work area, rolled up from the staging worklist (non-complete jobs only).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_queue_workload SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_queue_workload — populate in backfill phase)

-- ── Table: gold_wm_recipe_run_benchmark (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_recipe_run_benchmark IS
  'Recipe-line benchmark distribution for completed production runs. One row per plant_code × material_code × production_line, where null production_line is grouped as UNASSIGNED. Source: gold_wm_order_yield via dlt.read. Distribution includes only complete orders with goods receipt evidence (is_complete AND has_goods_receipt). run_count counts qualifying runs; yield percentiles ignore null yield_pct. Duration is last_gr_date - first_gr_date in hours and is null for zero/negative or missing GR date spans. No current_date()/current_timestamp() — deterministic base MV. cluster_by plant_code, material_code.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_recipe_run_benchmark SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_recipe_run_benchmark — populate in backfill phase)

-- ── Table: gold_wm_slow_movers (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_slow_movers IS
  'Value-weighted stock aging at plant x warehouse x material x batch grain: quantity, standard-price value, and the most recent movement timestamp. Query-time age and aging buckets live in the _live view. Interim (9xx) zones excluded.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_slow_movers SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_slow_movers — populate in backfill phase)

-- ── Table: gold_wm_staging_buffer_flow_hourly (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_buffer_flow_hourly IS
  'Hourly flows in and out of the palletising (bulk-drop) buffer from confirmed TO items: in = destination zone PALLETISING, out = source zone PALLETISING. The app reconstructs the buffer level B(t) by cumulating net flow and anchoring the latest point to current palletising-zone stock.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_buffer_flow_hourly SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_staging_buffer_flow_hourly — populate in backfill phase)

-- ── Table: gold_wm_staging_demand_hourly (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_demand_hourly IS
  'Planned staging demand wave: open TR quantity bucketed by planned execution hour and work area. Compared against gold_wm_staging_pace_hourly to show whether handlers are running ahead of or behind the wave.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_demand_hourly SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_staging_demand_hourly — populate in backfill phase)

-- ── Table: gold_wm_staging_pace_hourly (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_pace_hourly IS
  'Hourly material-handler throughput INTO staging buffers: confirmed TO items whose destination is a PALLETISING or PRODUCTION_SUPPLY zone, bucketed by confirmation hour. Derived from TO flows (bulk-drop log ZWMA_BULK_DROP_TO_LOG not yet replicated); feeds the staging-pace wave chart and the per-hour-of-day historical baselines (avg / best) that define what a good day looks like.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_pace_hourly SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_staging_pace_hourly — populate in backfill phase)

-- ── Table: gold_wm_staging_worklist (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_worklist IS
  'TR-header-grain supervisor worklist for warehouse staging and dispensary picking. One row per transfer requirement with derived work area (production staging / dispensary replenishment / dispensary picking), operational status from the site RF pick-status fields (blank=open, A=in progress, P=parked, N=no stock, C=complete), assigned RF operator/queue/campaign, and pick progress from linked transfer orders (LTAK.TBNUM). Carries deterministic demand_due_ts and a static intervention bump; query-time consumption views score urgency as overdue=100, <=2h=80, <=8h=60, <=24h=40, later=20, no demand date=10, plus +10 for PARKED/NO_STOCK. Read-only mirror of the ZWMAE0019_NEW Job Assignment grid.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_staging_worklist SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_staging_worklist — populate in backfill phase)

-- ── Table: gold_wm_supply_demand_ledger (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_supply_demand_ledger IS
  'Dated supply/demand ledger per plant_code × material_code for shortage projection. SUPPLY events: ON_HAND (batch_stock unrestricted qty, event_date NULL = current stock) and INBOUND_DELIVERY (open EL/ELST outbound_delivery lines with base-UOM qty only — PO lines excluded in v1 to avoid double-count with deliveries). DEMAND events: open reservation_requirement rows (movement 261 family, BDTER date). Window ordering: event_date NULLS FIRST, sort_seq (1=on-hand, 2=inbound, 3=demand), source_document_id. running_balance is cumulative signed_qty (+supply, −demand). UOM: same-material only; inbound restricted to delivery_quantity_base rows. Deterministic: no current_date(). cluster_by plant_code, material_code.';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_supply_demand_ledger SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_supply_demand_ledger — populate in backfill phase)

-- ── Table: gold_wm_worklist_summary (from wm_operations_gold.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.gold_io_reporting.gold_wm_worklist_summary IS
  'WM worklist rolled up by plant × warehouse × work area × status — the manager''s KPI strip (open / in-progress / parked / no-stock job counts per flow).';
ALTER TABLE connected_plant_uat.gold_io_reporting.gold_wm_worklist_summary SET TAGS (
  'layer' = 'gold',
  'product_area' = 'warehouse'
);
-- (no column comments yet for gold_wm_worklist_summary — populate in backfill phase)
