-- Unity Catalog Gold 'live' serving views (DEV).
-- Run once as a UC admin AFTER the secured-view SQL (gold_security_<env>.sql): each
-- _live view is built ON the matching *_secured view, so it inherits the plant row
-- filter (querying _live does NOT bypass RLS). Re-runnable (CREATE OR REPLACE).
-- These compute date-relative columns (current_date()) at query time so the base MVs
-- stay deterministic / incrementally refreshable (hardening plan Phase 2 / ADR 012).
-- WARNING: Generated by scripts/generate_gold_serving_views_sql.py. Do not edit by hand.

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_lineside_stock_live AS
SELECT
  b.*,
  CASE WHEN b.earliest_expiry_date IS NOT NULL THEN datediff(b.earliest_expiry_date, current_date()) END AS min_days_to_expiry
FROM connected_plant_dev.gold_io_reporting.gold_lineside_stock_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_lineside_stock_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_delivery_pick_status_live AS
SELECT
  b.*,
  datediff(b.planned_goods_issue_date, current_date()) AS days_to_goods_issue,
  CASE WHEN b.is_shipped THEN 'green' WHEN datediff(b.planned_goods_issue_date, current_date()) IS NULL THEN 'grey' WHEN coalesce(b.pick_fraction, 0.0) < 0.5 AND datediff(b.planned_goods_issue_date, current_date()) <= 0 THEN 'red' WHEN coalesce(b.pick_fraction, 0.0) < 0.8 AND datediff(b.planned_goods_issue_date, current_date()) <= 1 THEN 'amber' ELSE 'green' END AS risk_band
FROM connected_plant_dev.gold_io_reporting.gold_delivery_pick_status_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_delivery_pick_status_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_process_order_staging_live AS
SELECT
  b.*,
  datediff(b.scheduled_start_date, current_date()) AS days_to_start,
  CASE WHEN NOT coalesce(b.is_operationally_trusted, false) THEN 'unvalidated' WHEN b.to_items_total = 0 THEN 'grey' WHEN datediff(b.scheduled_start_date, current_date()) IS NULL THEN 'grey' WHEN coalesce(b.staging_fraction, 0.0) < 0.3 AND datediff(b.scheduled_start_date, current_date()) <= 0 THEN 'red' WHEN coalesce(b.staging_fraction, 0.0) < 0.7 AND datediff(b.scheduled_start_date, current_date()) <= 1 THEN 'amber' ELSE 'green' END AS risk_band
FROM connected_plant_dev.gold_io_reporting.gold_process_order_staging_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_process_order_staging_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_stock_expiry_risk_live AS
SELECT
  b.*,
  datediff(b.minimum_expiry_date, current_date()) AS minimum_days_to_expiry,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) < 0 THEN b.total_stock_qty END, 0.0) AS expired_qty,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) >= 0 AND datediff(b.minimum_expiry_date, current_date()) < 7 THEN b.total_stock_qty END, 0.0) AS expiry_risk_lt_7d_qty,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) >= 7 AND datediff(b.minimum_expiry_date, current_date()) < 30 THEN b.total_stock_qty END, 0.0) AS expiry_risk_7_30d_qty,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) >= 30 AND datediff(b.minimum_expiry_date, current_date()) < 90 THEN b.total_stock_qty END, 0.0) AS expiry_risk_30_90d_qty,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) >= 90 THEN b.total_stock_qty END, 0.0) AS expiry_ok_qty,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) < coalesce(b.minimum_remaining_shelf_life_days, 0) THEN b.total_stock_qty END, 0.0) AS minimum_shelf_life_breach_qty,
  CASE WHEN coalesce(b.total_stock_qty, 0.0) <= 0 THEN 'OK' WHEN datediff(b.minimum_expiry_date, current_date()) < 0 THEN 'EXPIRED' WHEN datediff(b.minimum_expiry_date, current_date()) < 7 THEN 'LT_7_DAYS' WHEN datediff(b.minimum_expiry_date, current_date()) < 30 THEN 'DAYS_7_30' WHEN datediff(b.minimum_expiry_date, current_date()) < 90 THEN 'DAYS_30_90' ELSE 'OK' END AS highest_expiry_risk_bucket,
  coalesce(CASE WHEN datediff(b.minimum_expiry_date, current_date()) < coalesce(b.minimum_remaining_shelf_life_days, 0) THEN b.total_stock_qty END, 0.0) > 0 AS has_minimum_shelf_life_breach
FROM connected_plant_dev.gold_io_reporting.gold_stock_expiry_risk_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_stock_expiry_risk_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_inbound_po_backlog_enhanced_live AS
SELECT
  b.*,
  CASE WHEN b.earliest_po_date IS NOT NULL THEN datediff(current_date(), b.earliest_po_date) END AS oldest_po_age_days,
  CASE WHEN b.remaining_open_qty <= 0 THEN 'green' WHEN datediff(current_date(), b.earliest_po_date) IS NULL THEN 'grey' WHEN datediff(current_date(), b.earliest_po_date) >= 30 THEN 'red' WHEN datediff(current_date(), b.earliest_po_date) >= 14 THEN 'amber' ELSE 'green' END AS inbound_backlog_risk_band
FROM connected_plant_dev.gold_io_reporting.gold_inbound_po_backlog_enhanced_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_inbound_po_backlog_enhanced_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_inbound_po_line_backlog_live AS
SELECT
  b.*,
  CASE WHEN b.po_date IS NOT NULL THEN datediff(current_date(), b.po_date) END AS oldest_po_age_days,
  CASE WHEN datediff(current_date(), b.po_date) IS NULL THEN 'grey' WHEN datediff(current_date(), b.po_date) >= 30 THEN 'red' WHEN datediff(current_date(), b.po_date) >= 14 THEN 'amber' ELSE 'green' END AS inbound_backlog_risk_band
FROM connected_plant_dev.gold_io_reporting.gold_inbound_po_line_backlog_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_inbound_po_line_backlog_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_warehouse_kpi_snapshot_live AS
SELECT
  b.*,
  current_date() AS snapshot_date
FROM connected_plant_dev.gold_io_reporting.gold_warehouse_kpi_snapshot_secured AS b;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_warehouse_kpi_snapshot_live TO `users`;

CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.gold_warehouse_exceptions_live AS
SELECT
  b.*,
  CAST(datediff(current_date(), b.aging_reference_date) AS INT) AS age_days,
  current_date() AS detected_date
FROM connected_plant_dev.gold_io_reporting.gold_warehouse_exceptions_secured AS b
WHERE CASE b.exception_type WHEN 'EXPIRED_BATCH_WITH_STOCK' THEN b.aging_reference_date < current_date() WHEN 'QI_STOCK_AGED_14D' THEN datediff(current_date(), b.aging_reference_date) > 14 WHEN 'BLOCKED_STOCK_AGED_3D' THEN datediff(current_date(), b.aging_reference_date) > 3 WHEN 'OPEN_TO_AGED_24H' THEN (unix_timestamp(current_timestamp()) - unix_timestamp(b.aging_reference_datetime)) / 3600.0 > 24 ELSE TRUE END;
GRANT SELECT ON VIEW connected_plant_dev.gold_io_reporting.gold_warehouse_exceptions_live TO `users`;
