-- Gold base-table access hardening (DEV). Generated by scripts/generate_gold_security_sql.py — do not edit manually.
-- Run as a UC admin AFTER gold_security_dev.sql (so the *_secured views already exist).
-- Revokes direct SELECT on the un-trimmed base Gold tables from the consumer group, so
-- plant-scoped users can only read the row-filtered *_secured views (ADR 012).

REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_transfer_order_performance FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_inbound_outbound_throughput FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_bin_occupancy FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_availability FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_transfer_requirement_backlog FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_expiry_risk FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_shift_output_summary FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_process_order_schedule_adherence FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_plant_production_quality_summary FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_process_order_operations FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_order_downtime_summary FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_process_order_component_status FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_dispensary_backlog FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_lineside_stock FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_delivery_pick_status FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_reconciliation FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_process_order_staging FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_process_order_staging_validation FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_storage_type_role_coverage_status FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_reconciliation_v2 FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_value_reconciliation FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_reconciliation_audit_log FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_movement_reconciliation FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_physical_inventory_recon FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_reconciliation_alerts FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_reconciliation_exceptions_v2 FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_reconciliation_summary_v2 FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_stock_reconciliation_summary FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_inbound_po_backlog FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_inbound_po_backlog_enhanced FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_warehouse_exceptions FROM `users`;
REVOKE SELECT ON TABLE connected_plant_dev.gold_io_reporting.gold_warehouse_kpi_snapshot FROM `users`;
