-- Unity Catalog base metadata — SILVER table annotations (UAT).
-- Generated by scripts/generate_base_metadata_sql.py — do not edit manually.
-- Run once as a UC admin after the DLT pipeline has created the tables.
-- Re-runnable: COMMENT ON and SET TAGS are idempotent (they overwrite existing values).
--
-- IMPORTANT: SET TAGS must be re-applied after any DLT full-refresh that re-creates the
-- table object (Databricks drops UC tags on table recreation).
--
-- Covers 52 table(s) across 9 metadata file(s).
-- Column comments are omitted where blank (P0 skeleton — populated in backfill phase).
--
-- UC syntax used:
--   COMMENT ON TABLE ... IS '...'          (table-level description, when non-empty)
--   ALTER TABLE ... SET TAGS (...)         (machine-readable governance tags)
--   COMMENT ON COLUMN ... IS '...'        (column-level descriptions, when non-empty)
--
-- Requires: APPLY TAG + MODIFY / OWNER on the target tables in connected_plant_uat.silver_io_reporting.

-- ── Table: handling_unit (from inbound.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.handling_unit IS
  'Handling units (VEKP/VEPO) — SSCC packing units with material, batch and delivery link';
ALTER TABLE connected_plant_uat.silver_io_reporting.handling_unit SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'warehouse360',
  'source_tables' = 'handlingunit_vekp,handlingunit_vepo'
);
-- (no column comments yet for handling_unit — populate in backfill phase)

-- ── Table: physical_inventory_document (from inbound.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.physical_inventory_document IS
  'Physical inventory documents (IKPF/ISEG) with book, counted and posted difference evidence';
ALTER TABLE connected_plant_uat.silver_io_reporting.physical_inventory_document SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'stock',
  'source_tables' = 'header_physical_inventory_doc_ikpf,physical_inventory_doc_items_iseg'
);
-- (no column comments yet for physical_inventory_document — populate in backfill phase)

-- ── Table: purchase_order (from inbound.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.purchase_order SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'procurementorderobject_ekko,procurementorderobject_ekpo'
);
-- (no column comments yet for purchase_order — populate in backfill phase)

-- ── Table: purchase_order_header_delete (from inbound.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.purchase_order_header_delete IS
  'Purchase-order headers with an EKKO delete tombstone. Used by Gold to suppress stale item-grain rows when item keys cannot be reconstructed.';
ALTER TABLE connected_plant_uat.silver_io_reporting.purchase_order_header_delete SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'procurementorderobject_ekko'
);
-- (no column comments yet for purchase_order_header_delete — populate in backfill phase)

-- ── Table: downtime_event (from process_order.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.downtime_event IS
  'Production downtime events (ZPEXPM_DWNT) — one row per order/operation/item downtime entry with reason and sub-reason. Current-state snapshot (source has no CDC sequencing metadata — AEDATTM only); soft-deleted rows (ZDEL=''X'') excluded.';
ALTER TABLE connected_plant_uat.silver_io_reporting.downtime_event SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'downtime_zpexpm_dwnt'
);
-- (no column comments yet for downtime_event — populate in backfill phase)

-- ── Table: pi_sheet_execution (from process_order.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.pi_sheet_execution IS
  'PI-sheet execution timing (ZMANPEX_E04_002) — one row per order/operation PI-sheet execution entry with start/end datetimes, duration, and user. Current-state snapshot (source has no CDC sequencing metadata — AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.pi_sheet_execution SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'actualpistartenddatetime_zmanpex_e04_002'
);
-- (no column comments yet for pi_sheet_execution — populate in backfill phase)

-- ── Table: process_order (from process_order.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.process_order SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'ordermaster_aufk,productionorderobject_afko,recipe_process_line'
);
-- (no column comments yet for process_order — populate in backfill phase)

-- ── Table: process_order_operation (from process_order.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.process_order_operation IS
  'Process-order operations (AFVC routing + AFVV quantities/dates) — one row per routing_number x operation_counter. Current-state snapshot (AFVV has no CDC sequencing metadata — AEDATTM only); AFVC soft-deletes (RecordActivity=''D'') excluded.';
ALTER TABLE connected_plant_uat.silver_io_reporting.process_order_operation SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'processorderobject_afvc,dbstructureoperationquantitydatevalues_afvv,productionorderobject_afko'
);
-- (no column comments yet for process_order_operation — populate in backfill phase)

-- ── Table: quality_inspection_characteristic (from quality.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_inspection_characteristic IS
  'MIC spec per inspection lot × operation × characteristic (QAMV) — one row per PRUEFLOS+VORGLFNR+MERKNR. Supplies SPC spec limits (nominal_target/usl_spec/lsl_spec) and characteristic metadata. Plant- and time-gated via the parent QALS lot under the spc gate (qm_enabled_flag AND spc_enabled_flag). Current-state snapshot (AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_inspection_characteristic SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'spc',
  'source_tables' = 'inspection_qamv,inspection_qals'
);
-- (no column comments yet for quality_inspection_characteristic — populate in backfill phase)

-- ── Table: quality_inspection_individual_result (from quality.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_inspection_individual_result IS
  'Individual inspection readings (QASE) — one row per PRUEFLOS+VORGLFNR+MERKNR+PROBENR+DETAILERG. MESSWERT is the RAW individual reading (NOT a sample mean — that is QASR.MITTELWERT). This is the deepest result grain, feeding SPC chart individual values. Plant- and time-gated via parent QALS lot under the spc gate. Current-state snapshot (AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_inspection_individual_result SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'spc',
  'source_tables' = 'inspection_qase,inspection_qals'
);
-- (no column comments yet for quality_inspection_individual_result — populate in backfill phase)

-- ── Table: quality_inspection_lot (from quality.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_inspection_lot IS
  'Quality inspection lots (QALS) — one row per lot, trace-relevant estate, rolling qm_lookback_years window (default 5y) on lot creation date. Gate: trace_lot = qm_enabled onboarded plants ∪ lifecycle NOT IN (SOLD/DIVESTED_ON_SAP) — ADR 016 §4. Fallback when site_lifecycle absent: qm_enabled set only (4-plant behaviour). Required by Final Trace (batch passport / journey QM context) across the estate. Current-state snapshot (QALS has no CDC sequencing metadata — AEDATTM only). Usage decisions live in the 1:many child quality_inspection_usage_decision, NOT on the lot. Result grain (QAMV/QAMR/QASR/QASE) deliberately NOT widened — stays on spc gate.';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_inspection_lot SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'trace_lot',
  'source_tables' = 'inspection_qals'
);
-- (no column comments yet for quality_inspection_lot — populate in backfill phase)

-- ── Table: quality_inspection_result (from quality.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_inspection_result IS
  'MIC-level inspection results (QAMR) — one row per PRUEFLOS+VORGLFNR+MERKNR. Contains quantitative/qualitative result, MBEWERTG accept/reject valuation, and result-recording dates (PRUEFDATUV/PRUEFDATUB — distinct from the lot''s planned inspection window PASTRTERM/PAENDTERM). Plant- and time-gated via parent QALS lot under the spc gate. Current-state snapshot (AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_inspection_result SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'spc',
  'source_tables' = 'inspection_qamr,inspection_qals'
);
-- (no column comments yet for quality_inspection_result — populate in backfill phase)

-- ── Table: quality_inspection_sample_result (from quality.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_inspection_sample_result IS
  'Per-sample inspection results (QASR) — one row per PRUEFLOS+VORGLFNR+MERKNR+PROBENR. MITTELWERT is the per-SAMPLE MEAN (aggregate over individual readings within the sample), distinct from QASE.MESSWERT which is the raw individual reading. Plant- and time-gated via parent QALS lot under the spc gate. Current-state snapshot (AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_inspection_sample_result SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'spc',
  'source_tables' = 'inspection_qasr,inspection_qals'
);
-- (no column comments yet for quality_inspection_sample_result — populate in backfill phase)

-- ── Table: quality_inspection_usage_decision (from quality.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_inspection_usage_decision IS
  'Usage decisions (QAVE) — one row per decision (PRUEFLOS+KZART+ZAEHLER); a lot can carry many. Accept/reject is VBEWERTUNG (A/R, confirmed from data), NOT the plant-configurable VCODE catalog code. Plant- and time-gated via the parent QALS lot (QAVE.VWERKS is the central responsible plant ''R001'', not the lot''s plant — gate-via-parent). Gate: trace_lot = qm_enabled onboarded plants ∪ lifecycle NOT IN (SOLD/DIVESTED_ON_SAP) — ADR 016 §4. Fallback when site_lifecycle absent: qm_enabled set only. Current-state snapshot (AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_inspection_usage_decision SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'trace_lot',
  'source_tables' = 'inspection_qave,inspection_qals'
);
-- (no column comments yet for quality_inspection_usage_decision — populate in backfill phase)

-- ── Table: quality_lab_characteristic_spec (from quality_lab.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_lab_characteristic_spec IS
  'Lab-board MIC spec limits (QAMV) — one row per PRUEFLOS+VORGLFNR+MERKNR. Supplies spec limits (lsl_spec/usl_spec) and, when replicated, warning limits (lsl_warn/usl_warn) for the lab-board severity rule (fail = outside spec, warn = within warning band). Rolling window (qm_lookback_years) and quality gate matching quality_lab_inspection_result. Current-state snapshot.';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_lab_characteristic_spec SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'spc',
  'source_tables' = 'inspection_qamv,inspection_qals'
);
-- (no column comments yet for quality_lab_characteristic_spec — populate in backfill phase)

-- ── Table: quality_lab_inspection_result (from quality_lab.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.quality_lab_inspection_result IS
  'Lab-board MIC-level inspection results (QAMR) — one row per PRUEFLOS+VORGLFNR+MERKNR. Rolling window (qm_lookback_years, default 5y) on lot creation date; quality gate (qm_enabled_flag only). UI day filter (ALL/360d/180d/30d) applied at query time on result recording date, not here. Designed for the lab-board wallboard gold layer (gold_qm_lab_result_signal). DO NOT merge with the SPC result-grain family (quality_inspection_result, spc gate) — they serve different product areas; this table reconciles with that one within the shared window once SPC Phase 1 merges. Current-state snapshot (AEDATTM only).';
ALTER TABLE connected_plant_uat.silver_io_reporting.quality_lab_inspection_result SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'DIRECT_PLANT',
  'layer' = 'silver',
  'product_area' = 'spc',
  'source_tables' = 'inspection_qamr,inspection_qals,inspection_qamv'
);
-- (no column comments yet for quality_lab_inspection_result — populate in backfill phase)

-- ── Table: batch_master (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.batch_master IS
  'Batch master — client-level MCH1 material/batch shelf-life attributes; no plant column in source.';
ALTER TABLE connected_plant_uat.silver_io_reporting.batch_master SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'stock',
  'source_tables' = 'crossplantbatch_mch1'
);
-- (no column comments yet for batch_master — populate in backfill phase)

-- ── Table: capacity_utilisation (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.capacity_utilisation IS
  'Classification of SAP movement types for warehouse, production, and inventory reporting';
ALTER TABLE connected_plant_uat.silver_io_reporting.capacity_utilisation SET TAGS (
  'current_status' = 'NEEDS_MAPPING',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'shiftparametersavailablecapacity_kapa,capacityheadersegment_kako'
);
-- (no column comments yet for capacity_utilisation — populate in backfill phase)

-- ── Table: customer (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.customer IS
  'Customer master — one row per customer (sold-to/ship-to), with name and address';
ALTER TABLE connected_plant_uat.silver_io_reporting.customer SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'customermaster_kna1'
);
-- (no column comments yet for customer — populate in backfill phase)

-- ── Table: material (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.material IS
  'Material master — one row per material per plant, with descriptions and compliance attributes';
ALTER TABLE connected_plant_uat.silver_io_reporting.material SET TAGS (
  'current_status' = 'NEEDS_MAPPING',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'materialmaster_mara,materialforplant_marc,materialdescription_makt'
);
-- (no column comments yet for material — populate in backfill phase)

-- ── Table: material_allergen (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.material_allergen IS
  'SAP classification-derived allergen map. Source: AUSP (KLART=''001'', ATINN=0000000849) joined to CAWNT (SPRAS=''E'') from central_services (published catalog). Grain: one row per material_code × allergen value (ATINN × ATZHL) — a material with multiple allergens produces multiple rows; do NOT collapse. AUSP.OBJEK for KLART=''001'' is the zero-padded MATNR directly (no INOB hop). Ungated and estate-wide: material classification has no WERKS dimension. Coverage caveat: ~25.7% of materials carry allergen classification (2026-06-12). Absence of a row means UNCLASSIFIED, NOT allergen-free — downstream joins must be LEFT and must NOT infer safety from silence.';
ALTER TABLE connected_plant_uat.silver_io_reporting.material_allergen SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'objectcharacteristics_ausp,characteristicvaluedescription_cawnt'
);
-- (no column comments yet for material_allergen — populate in backfill phase)

-- ── Table: material_uom_conversion (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.material_uom_conversion IS
  'SAP MARM alternate-unit conversion factors. qty_in_base_uom = qty_in_alt_uom * numerator / denominator. Base UoM per material is MARA-MEINS, available in silver.material.base_uom.';
ALTER TABLE connected_plant_uat.silver_io_reporting.material_uom_conversion SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'materialconversion_marm'
);
-- (no column comments yet for material_uom_conversion — populate in backfill phase)

-- ── Table: material_valuation (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.material_valuation IS
  'Material valuation and pricing per valuation area (MBEW)';
ALTER TABLE connected_plant_uat.silver_io_reporting.material_valuation SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'materialvaluation_mbew'
);
-- (no column comments yet for material_valuation — populate in backfill phase)

-- ── Table: movement_type_classification (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.movement_type_classification IS
  'Classification of SAP movement types for warehouse, production, and inventory reporting';
ALTER TABLE connected_plant_uat.silver_io_reporting.movement_type_classification SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'movementtype_t156,movementtypetext2_t156t'
);
-- (no column comments yet for movement_type_classification — populate in backfill phase)

-- ── Table: plant (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.plant IS
  'Plant master — one row per plant, with name, location and org assignments';
ALTER TABLE connected_plant_uat.silver_io_reporting.plant SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'plantcode_t001w'
);
-- (no column comments yet for plant — populate in backfill phase)

-- ── Table: recipe_process_line (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.recipe_process_line IS
  'Recipe/task-list (PLKO) → process-line classification map (SAP class type 018: " "recipe key → INOB → AUSP value → CAWNT English text). One row per recipe object key. " "process_order joins this for production_line enrichment. Lives in the slow (triggered) " "tier so the fast process_order stream reads a small pre-aggregated map instead of " "re-scanning AUSP every microbatch.';
ALTER TABLE connected_plant_uat.silver_io_reporting.recipe_process_line SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'internalnumberobjectlink_inob,objectcharacteristics_ausp,characteristicvaluedescription_cawnt'
);
-- (no column comments yet for recipe_process_line — populate in backfill phase)

-- ── Table: site_config_kpi_enablement (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_config_kpi_enablement IS
  'Conformed KPI enablement configuration inputs for readiness overrides';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_config_kpi_enablement SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'site_config_kpi_enablement_seed'
);
-- (no column comments yet for site_config_kpi_enablement — populate in backfill phase)

-- ── Table: site_config_movement_type_classification (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_config_movement_type_classification IS
  'Conformed movement type classification configuration inputs for readiness validation';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_config_movement_type_classification SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'site_config_movement_type_classification_seed'
);
-- (no column comments yet for site_config_movement_type_classification — populate in backfill phase)

-- ── Table: site_config_plant (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_config_plant IS
  'Conformed plant configuration inputs for readiness validation';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_config_plant SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'site_config_plant_seed'
);
-- (no column comments yet for site_config_plant — populate in backfill phase)

-- ── Table: site_config_staging_method (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_config_staging_method IS
  'Conformed staging method configuration inputs for readiness validation';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_config_staging_method SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'site_config_staging_method_seed'
);
-- (no column comments yet for site_config_staging_method — populate in backfill phase)

-- ── Table: site_config_storage_type_role (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_config_storage_type_role IS
  'Conformed storage type role configuration inputs for readiness validation';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_config_storage_type_role SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'site_config_storage_type_role_seed'
);
-- (no column comments yet for site_config_storage_type_role — populate in backfill phase)

-- ── Table: site_config_warehouse (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_config_warehouse IS
  'Conformed warehouse configuration inputs for readiness validation';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_config_warehouse SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'site_config_warehouse_seed'
);
-- (no column comments yet for site_config_warehouse — populate in backfill phase)

-- ── Table: site_lifecycle (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.site_lifecycle IS
  'Estate-wide site lifecycle dimension (~550 plants). effective_lifecycle ∈ ACTIVE / CLOSED / SOLD / DIVESTED_ON_SAP (ADR 016). Consumers filter on effective_lifecycle; this table serves all rows. Sourced from site_lifecycle_config (admin-seeded from site_lifecycle_review.csv).';
ALTER TABLE connected_plant_uat.silver_io_reporting.site_lifecycle SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'site_lifecycle_config_seed'
);
-- (no column comments yet for site_lifecycle — populate in backfill phase)

-- ── Table: stock_at_location (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.stock_at_location IS
  'IM book stock per material, plant and storage location (MARD)';
ALTER TABLE connected_plant_uat.silver_io_reporting.stock_at_location SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'stock',
  'source_tables' = 'storagelocationmaterial_mard'
);
-- (no column comments yet for stock_at_location — populate in backfill phase)

-- ── Table: storage_location (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.storage_location IS
  'Storage locations — one row per storage location per plant';
ALTER TABLE connected_plant_uat.silver_io_reporting.storage_location SET TAGS (
  'current_status' = 'NEEDS_MAPPING',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'storagelocation_t001l'
);
-- (no column comments yet for storage_location — populate in backfill phase)

-- ── Table: storage_type (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.storage_type IS
  'WM storage types — one row per warehouse number and storage type, with description';
ALTER TABLE connected_plant_uat.silver_io_reporting.storage_type SET TAGS (
  'current_status' = 'NEEDS_MAPPING',
  'gating_category' = 'B',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'wm_storagetypes_t301,wm_storagetypesdescription_t301t'
);
-- (no column comments yet for storage_type — populate in backfill phase)

-- ── Table: storage_type_role_mapping (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.storage_type_role_mapping IS
  'Mapping of storage types to specific functional roles (e.g. LINESIDE) per warehouse and plant';
ALTER TABLE connected_plant_uat.silver_io_reporting.storage_type_role_mapping SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'storage_role_config_seed'
);
-- (no column comments yet for storage_type_role_mapping — populate in backfill phase)

-- ── Table: vendor (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.vendor IS
  'Vendor master — one row per vendor, with name and address (LFA1)';
ALTER TABLE connected_plant_uat.silver_io_reporting.vendor SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'vendormaster_lfa1'
);
-- (no column comments yet for vendor — populate in backfill phase)

-- ── Table: warehouse_master (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.warehouse_master IS
  'T300 warehouse-number master (from central_services): one row per WM warehouse number.';
ALTER TABLE connected_plant_uat.silver_io_reporting.warehouse_master SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'warehousemaster_t300'
);
-- (no column comments yet for warehouse_master — populate in backfill phase)

-- ── Table: warehouse_storage_location_mapping (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.warehouse_storage_location_mapping IS
  'T320 storage-location to warehouse mapping (from central_services). Every (plant, storage_location) maps to exactly 1 warehouse; one warehouse may serve multiple storage-locations. Used to bridge IM sloc-grain data to WM warehouse-grain data.';
ALTER TABLE connected_plant_uat.silver_io_reporting.warehouse_storage_location_mapping SET TAGS (
  'current_status' = 'NEEDS_MAPPING',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'warehouseforplant_t320'
);
-- (no column comments yet for warehouse_storage_location_mapping — populate in backfill phase)

-- ── Table: work_centre (from reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.work_centre IS
  'Work centres — one row per work centre per plant, with descriptions " "(CRHD/CRTX from the published central_services catalog).';
ALTER TABLE connected_plant_uat.silver_io_reporting.work_centre SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'process_order',
  'source_tables' = 'workcenterheader_crhd,workcentertext_crtx'
);
-- (no column comments yet for work_centre — populate in backfill phase)

-- ── Table: batch_where_used (from traceability.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.batch_where_used IS
  'Batch where-used list (CHVW) — one row per consumption/transfer event involving a batch. Rolling trace_lookback_years window (default 5y) on posting date (BUDAT). Estate-wide: NOT filtered to WM/QM pilot plants — traceability traces the full supply chain across all active plants (ADR 016 §1; lifecycle gating of SOLD/DIVESTED edges applied at gold edge build T2 once lifecycle_status is populated). Current-state snapshot (CHVW is AEDATTM-only; no AERUNID/AERECNO).';
ALTER TABLE connected_plant_uat.silver_io_reporting.batch_where_used SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'traceability',
  'source_tables' = 'batchwhereusedlist_chvw'
);
-- (no column comments yet for batch_where_used — populate in backfill phase)

-- ── Table: batch_stock (from warehouse_fast.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.batch_stock IS
  'Batch stock current state (MCHB) — one row per material/plant/storage-location/batch; " "base_uom from MARA. Current-state snapshot (no CDC; MCHB has no apply_changes metadata).';
ALTER TABLE connected_plant_uat.silver_io_reporting.batch_stock SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'stock',
  'source_tables' = 'batchstock_mchb,materialmaster_mara'
);
-- (no column comments yet for batch_stock — populate in backfill phase)

-- ── Table: goods_movement (from warehouse_fast.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.goods_movement SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'inventorymovement_mseg,materialdocument_mkpf'
);
-- (no column comments yet for goods_movement — populate in backfill phase)

-- ── Table: warehouse_transfer_order (from warehouse_fast.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.warehouse_transfer_order SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'B',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'transferorderobjects_ltak,transferorderobjects_ltap'
);
-- (no column comments yet for warehouse_transfer_order — populate in backfill phase)

-- ── Table: warehouse_transfer_order_header_delete (from warehouse_fast.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.warehouse_transfer_order_header_delete IS
  'Transfer-order headers with an LTAK delete tombstone. Used by Gold to suppress stale item-grain rows when item keys cannot be reconstructed.';
ALTER TABLE connected_plant_uat.silver_io_reporting.warehouse_transfer_order_header_delete SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'transferorderobjects_ltak'
);
-- (no column comments yet for warehouse_transfer_order_header_delete — populate in backfill phase)

-- ── Table: warehouse_transfer_requirement (from warehouse_fast.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.warehouse_transfer_requirement SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'B',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'transferrequirementobjects_ltbk,transferrequirementobjects_ltbp'
);
-- (no column comments yet for warehouse_transfer_requirement — populate in backfill phase)

-- ── Table: outbound_delivery (from warehouse_flow.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.outbound_delivery SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'deliveryobjects_likp,deliveryobjects_lips'
);
-- (no column comments yet for outbound_delivery — populate in backfill phase)

-- ── Table: outbound_delivery_header_delete (from warehouse_flow.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.outbound_delivery_header_delete IS
  'Outbound-delivery headers with a LIKP delete tombstone. Used by Gold to suppress stale item-grain rows when item keys cannot be reconstructed.';
ALTER TABLE connected_plant_uat.silver_io_reporting.outbound_delivery_header_delete SET TAGS (
  'current_status' = 'EXEMPT',
  'gating_category' = 'D',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'deliveryobjects_likp'
);
-- (no column comments yet for outbound_delivery_header_delete — populate in backfill phase)

-- ── Table: reservation_requirement (from warehouse_flow.metadata.yml) ──
ALTER TABLE connected_plant_uat.silver_io_reporting.reservation_requirement SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'ioreporting',
  'source_tables' = 'reservationrequirement_resb'
);
-- (no column comments yet for reservation_requirement — populate in backfill phase)

-- ── Table: storage_bin (from warehouse_reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.storage_bin IS
  'Physical storage bins (LAGP) with current quant occupancy (LQUA). " "LQUA lacks physical delete markers (emptied quants are deleted upstream), so " "snapshot-CDC is used to prune vacated bins as their occupancy keys leave the snapshot.';
ALTER TABLE connected_plant_uat.silver_io_reporting.storage_bin SET TAGS (
  'current_status' = 'ENFORCED',
  'gating_category' = 'B',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'storagebin_lagp,quant_lqua,warehouse_plant_mapping'
);
-- (no column comments yet for storage_bin — populate in backfill phase)

-- ── Table: warehouse_plant_mapping (from warehouse_reference.metadata.yml) ──
COMMENT ON TABLE connected_plant_uat.silver_io_reporting.warehouse_plant_mapping IS
  'Warehouse to Plant mapping (SAP T320, sourced from the published/central_services catalog)';
ALTER TABLE connected_plant_uat.silver_io_reporting.warehouse_plant_mapping SET TAGS (
  'current_status' = 'NEEDS_MAPPING',
  'gating_category' = 'A',
  'layer' = 'silver',
  'product_area' = 'warehouse',
  'source_tables' = 'warehouseforplant_t320'
);
-- (no column comments yet for warehouse_plant_mapping — populate in backfill phase)
