-- SPC Serving Views (PROD)
-- Target: connected_plant_prod.gold_io_reporting
-- Creates the adapter-facing view spc_quality_metric_subgroup_mv that the SPC workspace
-- adapter (apps/api/adapters/spc/) resolves via SPC_CATALOG / SPC_SCHEMA (default "gold",
-- overridden to "gold_io_reporting" via app.yaml SPC_SCHEMA env var — see Step 3).
--
-- Run AFTER:
--   1. gold_pipeline first deploy (materialises gold_spc_quality_metric_subgroup)
--   2. gold_security_prod.sql (creates gold_spc_quality_metric_subgroup_secured)
-- WARNING: Generated by scripts infrastructure; re-runnable (CREATE OR REPLACE).
--
-- Migration note (2026-06-11): spc_locked_limits bridge view removed after
-- spc_state_migration_prod.sql promoted the table into gold_io_reporting directly.
-- The remaining three gold_* bridges (gold_batch_quality_result_v, gold_material,
-- gold_plant) are a SEPARATE concern and remain until their own governed replacements land.

USE CATALOG connected_plant_prod;
CREATE SCHEMA IF NOT EXISTS connected_plant_prod.gold_io_reporting;
USE SCHEMA gold_io_reporting;

-- Adapter-facing view: the SPC adapter resolves `spc_quality_metric_subgroup_mv` via
-- resolve_domain_object("spc", "spc_quality_metric_subgroup_mv") which produces
-- `<SPC_CATALOG>.<SPC_SCHEMA>.spc_quality_metric_subgroup_mv`. Set SPC_SCHEMA=gold_io_reporting
-- in app.yaml (or the relevant env config) to route the adapter to this view.
-- RLS is enforced in the upstream gold_spc_quality_metric_subgroup_secured view.
CREATE OR REPLACE VIEW connected_plant_prod.gold_io_reporting.spc_quality_metric_subgroup_mv AS
SELECT * FROM connected_plant_prod.gold_io_reporting.gold_spc_quality_metric_subgroup_secured;

-- ── Legacy-schema BRIDGE views ────────────────────────────────────────────────
-- The spc adapter resolves THREE remaining read-only objects through the same SPC_SCHEMA:
-- gold_batch_quality_result_v, gold_material, gold_plant. Until governed replacements exist,
-- bridge them to the legacy gold schema so the re-point does not break those endpoints.
-- These bridges are PART OF THE DECOMMISSION SCOPE: each disappears when its governed
-- replacement lands.
-- NOTE: spc_locked_limits bridge removed 2026-06-11; the table now lives directly in
-- gold_io_reporting (migrated via spc_state_migration_prod.sql).
CREATE OR REPLACE VIEW connected_plant_prod.gold_io_reporting.gold_batch_quality_result_v AS
SELECT * FROM connected_plant_prod.gold.gold_batch_quality_result_v;
CREATE OR REPLACE VIEW connected_plant_prod.gold_io_reporting.gold_material AS
SELECT * FROM connected_plant_prod.gold.gold_material;
CREATE OR REPLACE VIEW connected_plant_prod.gold_io_reporting.gold_plant AS
SELECT * FROM connected_plant_prod.gold.gold_plant;
