-- SPC Serving Views (DEV)
-- Target: connected_plant_dev.gold_io_reporting
-- Creates the adapter-facing view spc_quality_metric_subgroup_mv that the SPC workspace
-- adapter (apps/api/adapters/spc/) resolves via SPC_CATALOG / SPC_SCHEMA (default "gold",
-- overridden to "gold_io_reporting" via app.yaml SPC_SCHEMA env var — see Step 3).
--
-- Run AFTER:
--   1. gold_pipeline first deploy (materialises gold_spc_quality_metric_subgroup)
--   2. gold_security_dev.sql (creates gold_spc_quality_metric_subgroup_secured)
-- WARNING: Generated by scripts infrastructure; re-runnable (CREATE OR REPLACE).

USE CATALOG connected_plant_dev;
CREATE SCHEMA IF NOT EXISTS gold_io_reporting;
USE SCHEMA gold_io_reporting;

-- Adapter-facing view: the SPC adapter resolves `spc_quality_metric_subgroup_mv` via
-- resolve_domain_object("spc", "spc_quality_metric_subgroup_mv") which produces
-- `<SPC_CATALOG>.<SPC_SCHEMA>.spc_quality_metric_subgroup_mv`. Set SPC_SCHEMA=gold_io_reporting
-- in app.yaml (or the relevant env config) to route the adapter to this view.
-- Dev secured view is a pass-through (no RLS filter — no published_dev.security.model).
CREATE OR REPLACE VIEW connected_plant_dev.gold_io_reporting.spc_quality_metric_subgroup_mv AS
SELECT * FROM connected_plant_dev.gold_io_reporting.gold_spc_quality_metric_subgroup_secured;
