-- Traceability Capability-Tier Security — UAT
-- Target: connected_plant_uat.gold_io_reporting.gold_batch_lineage
--
-- TWO-TIER SECURITY MODEL (ADR 016 §3):
--
-- Gold MVs do NOT carry Unity Catalog row filters (doing so forces full MV refreshes on every
-- query — a Photon/DLT anti-pattern documented in ADR 005 / ADR 012).  Most Gold tables use
-- the 'io_reporting' CSM-backed *_secured serving views (generated by
-- scripts/generate_gold_security_sql.py) which implement plant-level RLS at query time.
--
-- gold_batch_lineage is DIFFERENT: it uses a CAPABILITY TIER instead of the standard RLS tier.
-- Rationale: traceability traversal is estate-wide by design (ADR 016 §1 — the graph must cross
-- plant boundaries to be useful), so plant-level RLS on the base MV would break graph traversals.
-- Instead:
--   • Tier 1 — Capability GRANT (this file): controlled group membership gates whether a user
--     can read the full estate-wide edge table at all.  The group ('traceability-readers') is
--     managed by the platform team and granted only to roles with a legitimate traceability need.
--   • Tier 2 — Anchor RLS (T3, future): the graph-search views apply per-user anchor filtering so
--     a user can only traverse from batches/orders they are authorised to see.  That layer is
--     delivered in T3 and references gold_batch_lineage as a source.
--
-- The 'traceability-readers' group may not exist yet in the UAT workspace.  This statement is
-- TOLERATED FAILURE: if the group is absent, the GRANT will fail gracefully with a Unity Catalog
-- "principal does not exist" error — this is expected and does not block the pipeline deployment.
-- Re-run after the group is provisioned.
--
-- Run AFTER the gold pipeline has materialised gold_batch_lineage for the first time.

USE CATALOG connected_plant_uat;
CREATE SCHEMA IF NOT EXISTS connected_plant_uat.gold_io_reporting;

GRANT SELECT ON TABLE connected_plant_uat.gold_io_reporting.gold_batch_lineage
  TO `traceability-readers`;

-- T4 (Phase 1 fan-out foundations): gold_batch_event_ledger and gold_trace_vendor.
-- Same capability-tier pattern as gold_batch_lineage above.
-- TOLERATED FAILURE: if the traceability-readers group is absent, these GRANTs will fail
-- gracefully — expected; re-run after provisioning.
GRANT SELECT ON TABLE connected_plant_uat.gold_io_reporting.gold_batch_event_ledger
  TO `traceability-readers`;

GRANT SELECT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_vendor
  TO `traceability-readers`;

-- T4 (Phase 3 enrichment lookups): gold_trace_material, gold_trace_plant, gold_trace_batch_material.
-- Same capability-tier pattern as gold_batch_lineage above.
-- TOLERATED FAILURE: if the traceability-readers group is absent, these GRANTs will fail
-- gracefully — expected; re-run after provisioning.
GRANT SELECT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_material
  TO `traceability-readers`;

GRANT SELECT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_plant
  TO `traceability-readers`;

GRANT SELECT ON TABLE connected_plant_uat.gold_io_reporting.gold_trace_batch_material
  TO `traceability-readers`;
