#!/usr/bin/env python3
"""CI guard: base DLT materialized views must be deterministic (hardening sprint rule).

Scans every `@dlt.table`-decorated function in the IOReporting gold/ and silver/ packages for
wall-clock expressions (`current_date`, `current_timestamp`, `now`, `unix_timestamp()` with no
argument). Time-relative columns belong in the `_live` serving views generated by
scripts/generate_gold_serving_views_sql.py (query time), never inside a base MV — wall-clock
expressions force full recomputes and make MV contents depend on when the refresh ran
(hardening plan Phase 2 / ADR 012).

Exemptions:
  * `@dlt.view` functions (e.g. the gold_freshness_gate expectation view) — views are not MVs;
  * monitoring/observability modules listed in EXEMPT_FILES (freshness + readiness validation
    tables intentionally stamp checked_at/observed_at audit timestamps and bound their scans
    to recent windows; they are full-recompute monitoring outputs, not analytics bases);
  * individual lines carrying a `# determinism-exempt` marker with a justifying comment
    (e.g. the governed-config validity window in silver/tables/reference.py).

Exit 0 = clean; exit 1 = violation (file:line listed).
"""
import ast
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "../.."))
PRODUCT = os.path.join(REPO_ROOT, "data-products/io-reporting")

SCAN_DIRS = ["gold", "silver"]

# Monitoring/observability modules: full-recompute tables whose audit timestamps
# (checked_at / latest_observed_at) and recent-window scans are the table's purpose.
EXEMPT_FILES = {
    "gold/freshness.py",
    "gold/readiness_validation.py",
}

MARKER = "# determinism-exempt"

WALL_CLOCK_FUNCS = {"current_date", "current_timestamp", "now", "localtimestamp"}


def _is_dlt_table_decorator(node: ast.expr) -> bool:
    """Matches @dlt.table and @dlt.table(...) (NOT @dlt.view)."""
    target = node.func if isinstance(node, ast.Call) else node
    return (
        isinstance(target, ast.Attribute)
        and target.attr == "table"
        and isinstance(target.value, ast.Name)
        and target.value.id == "dlt"
    )


def _wall_clock_calls(func: ast.FunctionDef) -> list[ast.Call]:
    calls = []
    for node in ast.walk(func):
        if not isinstance(node, ast.Call):
            continue
        name = None
        if isinstance(node.func, ast.Attribute):
            name = node.func.attr
        elif isinstance(node.func, ast.Name):
            name = node.func.id
        if name in WALL_CLOCK_FUNCS:
            calls.append(node)
        # unix_timestamp() with no args defaults to the current timestamp.
        elif name == "unix_timestamp" and not node.args and not node.keywords:
            calls.append(node)
    return calls


def scan_source(source: str, rel: str) -> list[str]:
    """Return violations for one module's source (pure — unit-testable)."""
    errors = []
    lines = source.splitlines()
    tree = ast.parse(source, filename=rel)
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if not any(_is_dlt_table_decorator(d) for d in node.decorator_list):
            continue
        for call in _wall_clock_calls(node):
            if MARKER in lines[call.lineno - 1]:
                continue
            errors.append(
                f"data-products/io-reporting/{rel}:{call.lineno}: wall-clock expression "
                f"inside @dlt.table '{node.name}' — base MVs must stay deterministic. "
                "Move it to the _live serving view "
                "(scripts/generate_gold_serving_views_sql.py) or, if genuinely "
                f"intended, justify it with a `{MARKER}` comment on the line."
            )
    return errors


def check() -> list[str]:
    errors = []
    for scan_dir in SCAN_DIRS:
        for dirpath, _dirnames, filenames in os.walk(os.path.join(PRODUCT, scan_dir)):
            for filename in sorted(filenames):
                if not filename.endswith(".py"):
                    continue
                path = os.path.join(dirpath, filename)
                rel = os.path.relpath(path, PRODUCT).replace(os.sep, "/")
                if rel in EXEMPT_FILES:
                    continue
                errors.extend(scan_source(open(path, encoding="utf-8").read(), rel))
    return errors


def main() -> int:
    errs = check()
    if errs:
        print("Gold/silver base-MV determinism guard: FAILED")
        for e in errs:
            print(f"  - {e}")
        return 1
    print("Gold/silver base-MV determinism guard: OK (no wall-clock expressions in @dlt.table functions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
