-- Silver row filters — UAT
-- Row filters on connected_plant_uat.silver_io_reporting have been removed.
-- Access control is enforced at schema level: the consumer group ('users') does not have
-- USAGE or SELECT on this schema. Plant-level filtering for consumers is applied at the
-- Gold secured-view layer via the published_<env>.security.model CSM pattern.
-- See scripts/generate_gold_security_sql.py and docs/adr/012-gold-row-level-security.md.
-- WARNING: Generated automatically by scripts/generate_row_filter_sql.py. Do not edit manually.
